// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::types::*;
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let client = CoreBamlClient::from_env()?;
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// TestComplexUnions - Generated BAML function
    pub async fn test_complex_unions(
        &self,
        input: String,
    ) -> BamlResult<crate::types::ComplexUnions> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestComplexUnions", context)
            .await
    }

    /// TestComplexUnions (streaming) - Generated BAML function  
    pub async fn test_complex_unions_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::ComplexUnions>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestComplexUnions", context)
            .await
    }
}
impl BamlClient {
    /// TestDiscriminatedUnions - Generated BAML function
    pub async fn test_discriminated_unions(
        &self,
        input: String,
    ) -> BamlResult<crate::types::DiscriminatedUnions> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestDiscriminatedUnions", context)
            .await
    }

    /// TestDiscriminatedUnions (streaming) - Generated BAML function  
    pub async fn test_discriminated_unions_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::DiscriminatedUnions>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestDiscriminatedUnions", context)
            .await
    }
}
impl BamlClient {
    /// TestPrimitiveUnions - Generated BAML function
    pub async fn test_primitive_unions(
        &self,
        input: String,
    ) -> BamlResult<crate::types::PrimitiveUnions> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestPrimitiveUnions", context)
            .await
    }

    /// TestPrimitiveUnions (streaming) - Generated BAML function  
    pub async fn test_primitive_unions_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::PrimitiveUnions>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestPrimitiveUnions", context)
            .await
    }
}
impl BamlClient {
    /// TestUnionArrays - Generated BAML function
    pub async fn test_union_arrays(&self, input: String) -> BamlResult<crate::types::UnionArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestUnionArrays", context).await
    }

    /// TestUnionArrays (streaming) - Generated BAML function  
    pub async fn test_union_arrays_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::UnionArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestUnionArrays", context)
            .await
    }
}
