// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use std::collections::HashMap;

pub fn baml_source_files() -> HashMap<&'static str, &'static str> {
    let mut map = HashMap::new();
    map.insert(
        "baml_src/main.baml",
        r###"class SemanticContainer {
    sixteen_digit_number int
    string_with_twenty_words string @stream.done
    class_1 ClassWithoutDone
    class_2 ClassWithBlockDone
    class_done_needed ClassWithBlockDone @stream.not_null
    class_needed ClassWithoutDone @stream.not_null
    three_small_things SmallThing[] @description("Should have three items.")
    final_string string
}

class ClassWithoutDone {
    i_16_digits int
    s_20_words string @description("A string with 20 words in it") @stream.with_state
}

class ClassWithBlockDone {
    i_16_digits int
    s_20_words string
    @@stream.done
}

class SmallThing {
    i_16_digits int @stream.not_null
    i_8_digits int
}

function MakeSemanticContainer() -> SemanticContainer {
    client "openai/gpt-4o"
    prompt #"
        {{ ctx.output_format }}
    "#
}

function MakeClassWithBlockDone() -> ClassWithBlockDone {
    client "openai/gpt-4o"
    prompt #"
        {{ ctx.output_format }}
    "#
}

function MakeClassWithExternalDone() -> ClassWithoutDone @stream.done {
    client "openai/gpt-4o"
    prompt #"
        {{ ctx.output_format }}
    "#
}"###,
    );
    map
}
