// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"primitive_types/baml_client/stream_types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type parse_stream struct{}

var ParseStream = &parse_stream{}

// / Parse version of TestEmptyCollections (Takes in string and returns stream_types.PrimitiveArrays)
func (*parse_stream) TestEmptyCollections(ctx context.Context, text string, opts ...CallOptionFunc) (stream_types.PrimitiveArrays, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestEmptyCollections: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestEmptyCollections", encoded)
	if err != nil {
		return stream_types.PrimitiveArrays{}, err
	}

	casted := (result).(stream_types.PrimitiveArrays)

	return casted, nil
}

// / Parse version of TestMixedPrimitives (Takes in string and returns stream_types.MixedPrimitives)
func (*parse_stream) TestMixedPrimitives(ctx context.Context, text string, opts ...CallOptionFunc) (stream_types.MixedPrimitives, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestMixedPrimitives: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestMixedPrimitives", encoded)
	if err != nil {
		return stream_types.MixedPrimitives{}, err
	}

	casted := (result).(stream_types.MixedPrimitives)

	return casted, nil
}

// / Parse version of TestPrimitiveArrays (Takes in string and returns stream_types.PrimitiveArrays)
func (*parse_stream) TestPrimitiveArrays(ctx context.Context, text string, opts ...CallOptionFunc) (stream_types.PrimitiveArrays, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveArrays: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestPrimitiveArrays", encoded)
	if err != nil {
		return stream_types.PrimitiveArrays{}, err
	}

	casted := (result).(stream_types.PrimitiveArrays)

	return casted, nil
}

// / Parse version of TestPrimitiveMaps (Takes in string and returns stream_types.PrimitiveMaps)
func (*parse_stream) TestPrimitiveMaps(ctx context.Context, text string, opts ...CallOptionFunc) (stream_types.PrimitiveMaps, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveMaps: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestPrimitiveMaps", encoded)
	if err != nil {
		return stream_types.PrimitiveMaps{}, err
	}

	casted := (result).(stream_types.PrimitiveMaps)

	return casted, nil
}

// / Parse version of TestPrimitiveTypes (Takes in string and returns stream_types.PrimitiveTypes)
func (*parse_stream) TestPrimitiveTypes(ctx context.Context, text string, opts ...CallOptionFunc) (stream_types.PrimitiveTypes, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveTypes: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestPrimitiveTypes", encoded)
	if err != nil {
		return stream_types.PrimitiveTypes{}, err
	}

	casted := (result).(stream_types.PrimitiveTypes)

	return casted, nil
}

// / Parse version of TestTopLevelBool (Takes in string and returns bool)
func (*parse_stream) TestTopLevelBool(ctx context.Context, text string, opts ...CallOptionFunc) (bool, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestTopLevelBool: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestTopLevelBool", encoded)
	if err != nil {
		return false, err
	}

	casted := (result).(bool)

	return casted, nil
}

// / Parse version of TestTopLevelFloat (Takes in string and returns float64)
func (*parse_stream) TestTopLevelFloat(ctx context.Context, text string, opts ...CallOptionFunc) (float64, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestTopLevelFloat: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestTopLevelFloat", encoded)
	if err != nil {
		return 0.0, err
	}

	casted := (result).(float64)

	return casted, nil
}

// / Parse version of TestTopLevelInt (Takes in string and returns int64)
func (*parse_stream) TestTopLevelInt(ctx context.Context, text string, opts ...CallOptionFunc) (int64, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestTopLevelInt: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestTopLevelInt", encoded)
	if err != nil {
		return 0, err
	}

	casted := (result).(int64)

	return casted, nil
}

// / Parse version of TestTopLevelNull (Takes in string and returns *interface{})
func (*parse_stream) TestTopLevelNull(ctx context.Context, text string, opts ...CallOptionFunc) (*interface{}, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestTopLevelNull: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestTopLevelNull", encoded)
	if err != nil {
		return (*interface{})(nil), err
	}

	casted := (result).(*interface{})

	return casted, nil
}

// / Parse version of TestTopLevelString (Takes in string and returns string)
func (*parse_stream) TestTopLevelString(ctx context.Context, text string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestTopLevelString: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestTopLevelString", encoded)
	if err != nil {
		return "", err
	}

	casted := (result).(string)

	return casted, nil
}
