// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

pub use baml_client_rust::StreamState;
pub use crate::types::*;

pub type Amount = Option<i64>;

pub type Combination = Option<crate::types::Union6BoolOrFloatOrIntOrListStringOrMapStringKeyListStringValueOrString>;

pub type Currency = Option<i64>;

pub type Graph = std::collections::HashMap<String, Vec<String>>;

pub type JsonArray = Vec<JsonValue>;

pub type JsonEntry = Option<Union2JsonTemplateOrSimpleTag>;

pub type JsonObject = std::collections::HashMap<String, JsonValue>;

pub type JsonTemplate = std::collections::HashMap<String, JsonEntry>;

pub type JsonValue = Option<Union6BoolOrFloatOrIntOrJsonArrayOrJsonObjectOrString>;

pub type LinkedListAlias = Option<crate::types::LinkedListAliasNode>;

pub type List = Vec<String>;

pub type MultipleAttrs = Option<i64>;

pub type NodeIndirection = Option<crate::types::NodeWithAliasIndirection>;

pub type Primitive = Option<crate::types::Union4BoolOrFloatOrIntOrString>;

pub type RecAliasOne = Option<RecAliasTwo>;

pub type RecAliasThree = Vec<RecAliasOne>;

pub type RecAliasTwo = Option<RecAliasThree>;

pub type RecursiveListAlias = Vec<RecursiveListAlias>;

pub type RecursiveMapAlias = std::collections::HashMap<String, RecursiveMapAlias>;

pub type RecursiveUnion = Option<Union2MapStringKeyRecursiveUnionValueOrString>;

pub type TodoTool = Option<Union2AddTodoItemOrTodoMessageToUser>;

