name: 'Setup Node.js and pnpm'
description: 'Setup Node.js with pnpm package manager'

inputs:
  install-dependencies:
    description: 'Whether to install dependencies with pnpm'
    required: false
    default: 'true'
  npm-token:
    description: 'NPM authentication token'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '9.12.0'
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        registry-url: "https://registry.npmjs.org"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Install Node dependencies
      if: inputs.install-dependencies == 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
