use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};
use functions::{render_async_client, render_globals, render_index, render_sync_client};
use generated_types::render_ts_types;
mod functions;
mod generated_types;
mod ir_to_ts;
mod package;
mod r#type;
mod utils;

#[derive(Default, Debug)]
pub struct TsLanguageFeatures;

impl LanguageFeatures for TsLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
        "#;

    fn name() -> &'static str {
        "typescript"
    }


    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let pkg = package::CurrentRenderPackage::new("baml_client", ir.clone());
        let file_map = args.file_map_as_json_string()?;
        let mut types: Vec<String> = ir
            .walk_classes()
            .map(|c| c.name().to_string())
            .chain(ir.walk_enums().map(|e| e.name().to_string()))
            .chain(ir.walk_alias_cycles().map(|a| a.item.0.clone()))
            .collect();
        types.sort();
        // collector.add_file("baml_source_map.ts", render_source_files(file_map)?);
        // collector.add_file("runtime.ts", render_runtime_code(&pkg)?);
        collector.add_file(
            "index.ts",
            render_index(&args.default_client_mode)?,
        )?;
        collector.add_file(
            "globals.ts",
            render_globals(&pkg)?,
        )?;
        let functions = ir
            .functions
            .iter()
            .map(|f| ir_to_ts::functions::ir_function_to_ts(f, &pkg))
            .collect::<Vec<_>>();
        collector.add_file(
            "async_client.ts",
            render_async_client(&functions, &types, &pkg)?,
        )?;
        collector.add_file(
            "sync_client.ts",
            render_sync_client(&functions, &types, &pkg)?,
        )?;
        // collector.add_file(
        //     "functions.ts",
        //     render_functions(&functions, &pkg, ts_mod_name)?,
        // );

        // collector.add_file(
        //     "functions_stream.ts",
        //     render_functions_stream(&functions, &pkg, ts_mod_name)?,
        // );

        let ts_classes = ir
            .walk_classes()
            .map(|c| ir_to_ts::classes::ir_class_to_ts(c.item, &pkg))
            .collect::<Vec<_>>();
        let ts_enums = ir
            .walk_enums()
            .map(|e| ir_to_ts::enums::ir_enum_to_ts(e.item, &pkg))
            .collect::<Vec<_>>();
        // let unions = {
        //     let mut unions = ir.walk_all_types()
        //                 .filter_map(|t| ir_to_ts::unions::ir_union_to_ts(t, &pkg))
        //                 .collect::<Vec<_>>();
        //     // dedup by name!
        //     unions.sort_by_key(|u| u.name.clone());
        //     unions.dedup_by_key(|u| u.name.clone());
        //     unions
        // };
        let mut type_aliases = ir
            .walk_type_aliases()
            .map(|a| ir_to_ts::type_aliases::ir_type_alias_to_ts(a.item, &pkg))
            .collect::<Vec<_>>();
        type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        // collector.add_file(
        //     "types.ts",
        //     render_types(&ts_classes)?,
        // );

        pkg.set("baml_client.types");
        collector.add_file(
            "types.ts",
            render_ts_types(&ts_enums, &ts_classes, &type_aliases, &pkg)?,
        );
        // collector.add_file(
        //     "partial_types.ts",
        //     render_partial_types(&ts_classes, &pkg)?,
        // );
        // collector.add_file(
        //     "types/enums.go",
        //     render_ts_types(&enums, &pkg)?,
        // );
        // collector.add_file(
        //     "types/unions.go",
        //     render_ts_types(&unions, &pkg)?,
        // );
        // collector.add_file(
        //     "types/type_aliases.go",
        //     render_ts_types(&type_aliases, &pkg)?,
        // );

        // let unions = {
        //     let mut unions = ir.walk_all_types()
        //                 .filter_map(|t| ir_to_ts::unions::ir_union_to_ts_stream(t, &pkg))
        //                 .collect::<Vec<_>>();
        //     // dedup by name!
        //     unions.sort_by_key(|u| u.name.clone());
        //     unions.dedup_by_key(|u| u.name.clone());
        //     unions
        // };

        // let type_aliases = ir
        //     .walk_type_aliases()
        //     .map(|c| ir_to_ts::type_aliases::ir_type_alias_to_ts_stream(c.item, &pkg))
        //     .collect::<Vec<_>>();

        pkg.set("baml_client.stream_types");
        // collector.add_file(
        //     "stream_types/utils.ts",
        //     render_ts_stream_types_utils(&pkg)?,
        // );
        // collector.add_file(
        //     "stream_types/classes.ts",
        //     render_ts_stream_types(&ts_classes, &pkg)?,
        // );
        // collector.add_file(
        //     "stream_types/unions.ts",
        //     render_ts_stream_types(&unions, &pkg)?,
        // );
        // collector.add_file(
        //     "stream_types/type_aliases.ts",
        //     render_ts_stream_types(&type_aliases, &pkg)?,
        // );

        Ok(())
    }
}


#[cfg(test)]
mod generated_tests {
    use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};

    impl TestLanguageFeatures for crate::TsLanguageFeatures {
        fn test_name() -> &'static str {
            "typescript"
        }
    }

    create_code_gen_test_suites!(crate::TsLanguageFeatures);
}

#[cfg(test)]
mod tests {
   #[test]
    fn test_name() {
        use std::str::FromStr;
        use dir_writer::LanguageFeatures;

        let gen_type = baml_types::GeneratorOutputType::from_str(crate::TsLanguageFeatures::name())
            .expect("TsLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Typescript);
    }
}
