name: "Setup Ruby"
description: "Setup Ruby with optional version selection"

runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
