// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Person {
    pub name: String,

    pub age: String,
}

impl Person {
    /// Create a new Person instance
    pub fn new(name: String, age: String) -> Self {
        Self { name, age }
    }
}

impl Default for Person {
    fn default() -> Self {
        Self::new(String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Person {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("age".to_string(), self.age.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Person".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Person {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Person"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let age = map
                    .get("age")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'age' in Person"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(name, age))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}
