// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::types::*;
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let client = CoreBamlClient::from_env()?;
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// TestAllNull - Generated BAML function
    pub async fn test_all_null(&self, input: String) -> BamlResult<crate::types::NullableTypes> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestAllNull", context).await
    }

    /// TestAllNull (streaming) - Generated BAML function  
    pub async fn test_all_null_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::NullableTypes>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestAllNull", context)
            .await
    }
}
impl BamlClient {
    /// TestAllOptionalOmitted - Generated BAML function
    pub async fn test_all_optional_omitted(
        &self,
        input: String,
    ) -> BamlResult<crate::types::OptionalFields> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestAllOptionalOmitted", context)
            .await
    }

    /// TestAllOptionalOmitted (streaming) - Generated BAML function  
    pub async fn test_all_optional_omitted_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::OptionalFields>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestAllOptionalOmitted", context)
            .await
    }
}
impl BamlClient {
    /// TestMixedOptionalNullable - Generated BAML function
    pub async fn test_mixed_optional_nullable(
        &self,
        input: String,
    ) -> BamlResult<crate::types::MixedOptionalNullable> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestMixedOptionalNullable", context)
            .await
    }

    /// TestMixedOptionalNullable (streaming) - Generated BAML function  
    pub async fn test_mixed_optional_nullable_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<crate::types::MixedOptionalNullable>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestMixedOptionalNullable", context)
            .await
    }
}
impl BamlClient {
    /// TestNullableTypes - Generated BAML function
    pub async fn test_nullable_types(
        &self,
        input: String,
    ) -> BamlResult<crate::types::NullableTypes> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestNullableTypes", context)
            .await
    }

    /// TestNullableTypes (streaming) - Generated BAML function  
    pub async fn test_nullable_types_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::NullableTypes>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestNullableTypes", context)
            .await
    }
}
impl BamlClient {
    /// TestOptionalFields - Generated BAML function
    pub async fn test_optional_fields(
        &self,
        input: String,
    ) -> BamlResult<crate::types::OptionalFields> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestOptionalFields", context)
            .await
    }

    /// TestOptionalFields (streaming) - Generated BAML function  
    pub async fn test_optional_fields_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::OptionalFields>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestOptionalFields", context)
            .await
    }
}
