// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::types::*;
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let client = CoreBamlClient::from_env()?;
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// TestComplexMaps - Generated BAML function
    pub async fn test_complex_maps(&self, input: String) -> BamlResult<crate::types::ComplexMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestComplexMaps", context).await
    }

    /// TestComplexMaps (streaming) - Generated BAML function  
    pub async fn test_complex_maps_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::ComplexMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestComplexMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestEdgeCaseMaps - Generated BAML function
    pub async fn test_edge_case_maps(
        &self,
        input: String,
    ) -> BamlResult<crate::types::EdgeCaseMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestEdgeCaseMaps", context).await
    }

    /// TestEdgeCaseMaps (streaming) - Generated BAML function  
    pub async fn test_edge_case_maps_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::EdgeCaseMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestEdgeCaseMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestLargeMaps - Generated BAML function
    pub async fn test_large_maps(&self, input: String) -> BamlResult<crate::types::SimpleMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestLargeMaps", context).await
    }

    /// TestLargeMaps (streaming) - Generated BAML function  
    pub async fn test_large_maps_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::SimpleMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestLargeMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestNestedMaps - Generated BAML function
    pub async fn test_nested_maps(&self, input: String) -> BamlResult<crate::types::NestedMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestNestedMaps", context).await
    }

    /// TestNestedMaps (streaming) - Generated BAML function  
    pub async fn test_nested_maps_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::NestedMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestNestedMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestSimpleMaps - Generated BAML function
    pub async fn test_simple_maps(&self, input: String) -> BamlResult<crate::types::SimpleMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("TestSimpleMaps", context).await
    }

    /// TestSimpleMaps (streaming) - Generated BAML function  
    pub async fn test_simple_maps_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::SimpleMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestSimpleMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelBoolMap - Generated BAML function
    pub async fn test_top_level_bool_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, bool>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelBoolMap", context)
            .await
    }

    /// TestTopLevelBoolMap (streaming) - Generated BAML function  
    pub async fn test_top_level_bool_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, bool>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelBoolMap", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelEmptyMap - Generated BAML function
    pub async fn test_top_level_empty_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, String>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelEmptyMap", context)
            .await
    }

    /// TestTopLevelEmptyMap (streaming) - Generated BAML function  
    pub async fn test_top_level_empty_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, String>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelEmptyMap", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelFloatMap - Generated BAML function
    pub async fn test_top_level_float_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, f64>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelFloatMap", context)
            .await
    }

    /// TestTopLevelFloatMap (streaming) - Generated BAML function  
    pub async fn test_top_level_float_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, f64>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelFloatMap", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelIntMap - Generated BAML function
    pub async fn test_top_level_int_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, i64>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelIntMap", context)
            .await
    }

    /// TestTopLevelIntMap (streaming) - Generated BAML function  
    pub async fn test_top_level_int_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, i64>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelIntMap", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelMapOfArrays - Generated BAML function
    pub async fn test_top_level_map_of_arrays(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, Vec<i64>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelMapOfArrays", context)
            .await
    }

    /// TestTopLevelMapOfArrays (streaming) - Generated BAML function  
    pub async fn test_top_level_map_of_arrays_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, Vec<i64>>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelMapOfArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelMapOfObjects - Generated BAML function
    pub async fn test_top_level_map_of_objects(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, crate::types::User>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelMapOfObjects", context)
            .await
    }

    /// TestTopLevelMapOfObjects (streaming) - Generated BAML function  
    pub async fn test_top_level_map_of_objects_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<
                        std::collections::HashMap<String, crate::types::User>,
                    >,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelMapOfObjects", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelMapWithNullable - Generated BAML function
    pub async fn test_top_level_map_with_nullable(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, Option<String>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelMapWithNullable", context)
            .await
    }

    /// TestTopLevelMapWithNullable (streaming) - Generated BAML function  
    pub async fn test_top_level_map_with_nullable_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<
                        std::collections::HashMap<String, Option<String>>,
                    >,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelMapWithNullable", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelNestedMap - Generated BAML function
    pub async fn test_top_level_nested_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, std::collections::HashMap<String, String>>>
    {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelNestedMap", context)
            .await
    }

    /// TestTopLevelNestedMap (streaming) - Generated BAML function  
    pub async fn test_top_level_nested_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<
                        std::collections::HashMap<
                            String,
                            std::collections::HashMap<String, String>,
                        >,
                    >,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelNestedMap", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelStringMap - Generated BAML function
    pub async fn test_top_level_string_map(
        &self,
        input: String,
    ) -> BamlResult<std::collections::HashMap<String, String>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("TestTopLevelStringMap", context)
            .await
    }

    /// TestTopLevelStringMap (streaming) - Generated BAML function  
    pub async fn test_top_level_string_map_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<std::collections::HashMap<String, String>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("TestTopLevelStringMap", context)
            .await
    }
}
