// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplexMaps {
    pub userMap: String,

    pub productMap: String,

    pub nestedMap: String,

    pub arrayMap: String,

    pub mapArray: String,
}

impl ComplexMaps {
    /// Create a new ComplexMaps instance
    pub fn new(
        userMap: String,
        productMap: String,
        nestedMap: String,
        arrayMap: String,
        mapArray: String,
    ) -> Self {
        Self {
            userMap,
            productMap,
            nestedMap,
            arrayMap,
            mapArray,
        }
    }
}

impl Default for ComplexMaps {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ComplexMaps {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("userMap".to_string(), self.userMap.to_baml_value()?);
        map.insert("productMap".to_string(), self.productMap.to_baml_value()?);
        map.insert("nestedMap".to_string(), self.nestedMap.to_baml_value()?);
        map.insert("arrayMap".to_string(), self.arrayMap.to_baml_value()?);
        map.insert("mapArray".to_string(), self.mapArray.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "ComplexMaps".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ComplexMaps {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let userMap = map
                    .get("userMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'userMap' in ComplexMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let productMap = map
                    .get("productMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'productMap' in ComplexMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nestedMap = map
                    .get("nestedMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nestedMap' in ComplexMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let arrayMap = map
                    .get("arrayMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'arrayMap' in ComplexMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mapArray = map
                    .get("mapArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mapArray' in ComplexMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    userMap, productMap, nestedMap, arrayMap, mapArray,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub url: String,

    pub port: String,

    pub debug: String,
}

impl Config {
    /// Create a new Config instance
    pub fn new(url: String, port: String, debug: String) -> Self {
        Self { url, port, debug }
    }
}

impl Default for Config {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Config {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("url".to_string(), self.url.to_baml_value()?);
        map.insert("port".to_string(), self.port.to_baml_value()?);
        map.insert("debug".to_string(), self.debug.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Config".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Config {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let url = map
                    .get("url")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'url' in Config"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let port = map
                    .get("port")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'port' in Config"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let debug = map
                    .get("debug")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'debug' in Config"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(url, port, debug))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeCaseMaps {
    pub emptyMap: String,

    pub nullableValues: String,

    pub optionalValues: String,

    pub unionValues: String,
}

impl EdgeCaseMaps {
    /// Create a new EdgeCaseMaps instance
    pub fn new(
        emptyMap: String,
        nullableValues: String,
        optionalValues: String,
        unionValues: String,
    ) -> Self {
        Self {
            emptyMap,
            nullableValues,
            optionalValues,
            unionValues,
        }
    }
}

impl Default for EdgeCaseMaps {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for EdgeCaseMaps {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("emptyMap".to_string(), self.emptyMap.to_baml_value()?);
        map.insert(
            "nullableValues".to_string(),
            self.nullableValues.to_baml_value()?,
        );
        map.insert(
            "optionalValues".to_string(),
            self.optionalValues.to_baml_value()?,
        );
        map.insert("unionValues".to_string(), self.unionValues.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "EdgeCaseMaps".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for EdgeCaseMaps {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let emptyMap = map
                    .get("emptyMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyMap' in EdgeCaseMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableValues = map
                    .get("nullableValues")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableValues' in EdgeCaseMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalValues = map
                    .get("optionalValues")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalValues' in EdgeCaseMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let unionValues = map
                    .get("unionValues")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'unionValues' in EdgeCaseMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    emptyMap,
                    nullableValues,
                    optionalValues,
                    unionValues,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MixedKeyMaps {
    pub stringIntMap: String,

    pub intStringMap: String,

    pub enumMap: String,

    pub literalMap: String,
}

impl MixedKeyMaps {
    /// Create a new MixedKeyMaps instance
    pub fn new(
        stringIntMap: String,
        intStringMap: String,
        enumMap: String,
        literalMap: String,
    ) -> Self {
        Self {
            stringIntMap,
            intStringMap,
            enumMap,
            literalMap,
        }
    }
}

impl Default for MixedKeyMaps {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedKeyMaps {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "stringIntMap".to_string(),
            self.stringIntMap.to_baml_value()?,
        );
        map.insert(
            "intStringMap".to_string(),
            self.intStringMap.to_baml_value()?,
        );
        map.insert("enumMap".to_string(), self.enumMap.to_baml_value()?);
        map.insert("literalMap".to_string(), self.literalMap.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedKeyMaps".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedKeyMaps {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let stringIntMap = map
                    .get("stringIntMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringIntMap' in MixedKeyMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let intStringMap = map
                    .get("intStringMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'intStringMap' in MixedKeyMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let enumMap = map
                    .get("enumMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'enumMap' in MixedKeyMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let literalMap = map
                    .get("literalMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'literalMap' in MixedKeyMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(stringIntMap, intStringMap, enumMap, literalMap))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NestedMaps {
    pub simple: String,

    pub oneLevelNested: String,

    pub twoLevelNested: String,

    pub mapOfArrays: String,

    pub mapOfMaps: String,
}

impl NestedMaps {
    /// Create a new NestedMaps instance
    pub fn new(
        simple: String,
        oneLevelNested: String,
        twoLevelNested: String,
        mapOfArrays: String,
        mapOfMaps: String,
    ) -> Self {
        Self {
            simple,
            oneLevelNested,
            twoLevelNested,
            mapOfArrays,
            mapOfMaps,
        }
    }
}

impl Default for NestedMaps {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NestedMaps {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("simple".to_string(), self.simple.to_baml_value()?);
        map.insert(
            "oneLevelNested".to_string(),
            self.oneLevelNested.to_baml_value()?,
        );
        map.insert(
            "twoLevelNested".to_string(),
            self.twoLevelNested.to_baml_value()?,
        );
        map.insert("mapOfArrays".to_string(), self.mapOfArrays.to_baml_value()?);
        map.insert("mapOfMaps".to_string(), self.mapOfMaps.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "NestedMaps".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NestedMaps {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let simple = map
                    .get("simple")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'simple' in NestedMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let oneLevelNested = map
                    .get("oneLevelNested")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'oneLevelNested' in NestedMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let twoLevelNested = map
                    .get("twoLevelNested")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'twoLevelNested' in NestedMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mapOfArrays = map
                    .get("mapOfArrays")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mapOfArrays' in NestedMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mapOfMaps = map
                    .get("mapOfMaps")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mapOfMaps' in NestedMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    simple,
                    oneLevelNested,
                    twoLevelNested,
                    mapOfArrays,
                    mapOfMaps,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Product {
    pub id: String,

    pub name: String,

    pub price: String,

    pub tags: String,
}

impl Product {
    /// Create a new Product instance
    pub fn new(id: String, name: String, price: String, tags: String) -> Self {
        Self {
            id,
            name,
            price,
            tags,
        }
    }
}

impl Default for Product {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Product {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("price".to_string(), self.price.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Product".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Product {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let price = map
                    .get("price")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'price' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let tags = map
                    .get("tags")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, price, tags))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimpleMaps {
    pub stringToString: String,

    pub stringToInt: String,

    pub stringToFloat: String,

    pub stringToBool: String,

    pub intToString: String,
}

impl SimpleMaps {
    /// Create a new SimpleMaps instance
    pub fn new(
        stringToString: String,
        stringToInt: String,
        stringToFloat: String,
        stringToBool: String,
        intToString: String,
    ) -> Self {
        Self {
            stringToString,
            stringToInt,
            stringToFloat,
            stringToBool,
            intToString,
        }
    }
}

impl Default for SimpleMaps {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for SimpleMaps {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "stringToString".to_string(),
            self.stringToString.to_baml_value()?,
        );
        map.insert("stringToInt".to_string(), self.stringToInt.to_baml_value()?);
        map.insert(
            "stringToFloat".to_string(),
            self.stringToFloat.to_baml_value()?,
        );
        map.insert(
            "stringToBool".to_string(),
            self.stringToBool.to_baml_value()?,
        );
        map.insert("intToString".to_string(), self.intToString.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "SimpleMaps".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for SimpleMaps {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let stringToString = map
                    .get("stringToString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringToString' in SimpleMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let stringToInt = map
                    .get("stringToInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringToInt' in SimpleMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let stringToFloat = map
                    .get("stringToFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringToFloat' in SimpleMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let stringToBool = map
                    .get("stringToBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringToBool' in SimpleMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let intToString = map
                    .get("intToString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'intToString' in SimpleMaps"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    stringToString,
                    stringToInt,
                    stringToFloat,
                    stringToBool,
                    intToString,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub id: String,

    pub name: String,

    pub email: String,

    pub active: String,
}

impl User {
    /// Create a new User instance
    pub fn new(id: String, name: String, email: String, active: String) -> Self {
        Self {
            id,
            name,
            email,
            active,
        }
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for User {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("email".to_string(), self.email.to_baml_value()?);
        map.insert("active".to_string(), self.active.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "User".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for User {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let email = map
                    .get("email")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'email' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let active = map
                    .get("active")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'active' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, email, active))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Status {
    /// ACTIVE variant
    ACTIVE,
    /// INACTIVE variant
    INACTIVE,
    /// PENDING variant
    PENDING,
}

impl Status {
    /// Get all possible values for this enum
    pub fn values() -> Vec<Self> {
        vec![Self::ACTIVE, Self::INACTIVE, Self::PENDING]
    }

    /// Get the string representation of this enum variant
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ACTIVE => "ACTIVE",
            Self::INACTIVE => "INACTIVE",
            Self::PENDING => "PENDING",
        }
    }

    /// Create enum from string, if valid
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "ACTIVE" => Some(Self::ACTIVE),
            "INACTIVE" => Some(Self::INACTIVE),
            "PENDING" => Some(Self::PENDING),
            _ => None,
        }
    }

    /// Check if this enum variant is valid
    pub fn is_valid(&self) -> bool {
        Self::values().contains(self)
    }
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl std::str::FromStr for Status {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::from_str(s).ok_or_else(|| {
            format!(
                "Invalid Status value: '{}'. Valid values are: [{}]",
                s,
                Self::values()
                    .iter()
                    .map(|v| v.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        })
    }
}

impl Default for Status {
    fn default() -> Self {
        Self::ACTIVE
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Status {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        Ok(baml_client_rust::types::BamlValue::Enum(
            "Status".to_string(),
            self.as_str().to_string(),
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Status {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Enum(_enum_name, variant) => {
                Self::from_str(&variant)
                    .map_err(|e| baml_client_rust::BamlError::deserialization(e))
            }
            baml_client_rust::types::BamlValue::String(s) => {
                Self::from_str(&s).map_err(|e| baml_client_rust::BamlError::deserialization(e))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected enum, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3BoolOrIntOrString {
    String(String),
    Int(i64),
    Bool(bool),
}

impl Union3BoolOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union3BoolOrIntOrString
impl Union3BoolOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3BoolOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}
