/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface Activity {
  name: string
  location: string
  price_dollars: number
  
}

export interface Flight {
  source: string
  dest: string
  datetime: string
  
}

export interface Itinerary {
  flights: Flight[]
  activities: Activity[]
  
}

export interface Message {
  sender: "user" | "agent"
  content: string
  
}

export interface RequestInfoFromUser {
  type: "request_info_from_user"
  message_to_user: string
  
}

export interface SearchFlights {
  type: "search_flights"
  
}

export interface SetItinerary {
  type: "set_itinerary"
  itinerary: Itinerary
  
}

export interface TravelAgentContext {
  nAdults?: number | null
  nChildren?: number | null
  interests: string[]
  homeLocation?: string | null
  dateRange?: string | null
  
}

export interface UpdateTravelAgentContext {
  type: "update_travel_agent_context"
  new_context: TravelAgentContext
  
}

export type Tool = RequestInfoFromUser | UpdateTravelAgentContext | SearchFlights
