use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};
use functions::{render_functions, render_source_files};
use std::sync::OnceLock;

use baml_types::ir_type::{TypeGeneric, TypeNonStreaming, UnionTypeViewGeneric};

mod functions;
mod generated_types;
mod ir_to_rust;
mod package;
mod r#type;
mod utils;

fn type_generic_matches_class(
    t: &TypeGeneric<baml_types::ir_type::type_meta::NonStreaming>,
    class_name: &str,
) -> bool {
    match t {
        TypeGeneric::Class { name, .. } => name == class_name,
        TypeGeneric::RecursiveTypeAlias { name, .. } => name == class_name,
        _ => false,
    }
}

fn union_contains_class(field_type: &TypeNonStreaming, class_name: &str) -> bool {
    match field_type {
        TypeGeneric::Union(union_generic, _) => match union_generic.view() {
            UnionTypeViewGeneric::Null => false,
            UnionTypeViewGeneric::Optional(inner) => type_generic_matches_class(inner, class_name),
            UnionTypeViewGeneric::OneOf(types) | UnionTypeViewGeneric::OneOfOptional(types) => {
                types
                    .iter()
                    .any(|t| type_generic_matches_class(t, class_name))
            }
        },
        _ => false,
    }
}

#[derive(Default)]
pub struct RustLanguageFeatures {
    generation_timestamp: OnceLock<String>,
}

impl LanguageFeatures for RustLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli
        "#;

    fn name() -> &'static str {
        "rust"
    }

    fn on_file_created(&self, path: &std::path::Path, content: &mut String) -> anyhow::Result<()> {
        // Skip adding prefix for TOML files since they use # for comments, not //
        if path.extension().and_then(|s| s.to_str()) == Some("toml") {
            return Ok(());
        }

        // Add prefix for Rust source files
        content.push_str(self.content_prefix());
        content.push('\n');
        Ok(())
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let pkg = package::CurrentRenderPackage::new("baml_client", ir.clone());
        let file_map = args.file_map_as_json_string()?;

        // Generate core files - put Rust source files in src/ directory
        collector.add_file("src/source_map.rs", render_source_files(file_map)?)?;
        collector.add_file("src/lib.rs", render_lib_rs(&pkg)?)?;
        collector.add_file("Cargo.toml", self.render_cargo_toml()?)?;

        // Generate function clients
        let functions = ir
            .functions
            .iter()
            .map(|f| ir_to_rust::functions::ir_function_to_rust(f, &pkg))
            .collect::<Vec<_>>();
        collector.add_file("src/client.rs", render_functions(&functions, &pkg)?)?;

        // Generate types
        let rust_classes: Vec<generated_types::ClassRust> = ir
            .walk_classes()
            .map(|c| {
                let class_data = ir_to_rust::classes::ir_class_to_rust(c.item, &pkg);
                let class_name = class_data.name.clone();
                generated_types::ClassRust {
                    name: class_data.name,
                    docstring: None, // TODO: Extract docstring from class
                    fields: class_data
                        .fields
                        .into_iter()
                        .map(|field| {
                            let class_name = &class_name;
                            // Convert field type from string back to TypeRust
                            // For now, we need to re-parse the field type properly
                            let field_type_ir = c
                                .item
                                .elem
                                .static_fields
                                .iter()
                                .find(|f| {
                                    let snake = crate::utils::to_snake_case(&f.elem.name);
                                    crate::utils::safe_rust_identifier(&snake) == field.name
                                })
                                .map(|f| &f.elem.r#type.elem);

                            let mut rust_type = if let Some(field_type) = field_type_ir {
                                let field_type_non_streaming =
                                    field_type.to_non_streaming_type(pkg.lookup());
                                let mut ty = crate::ir_to_rust::type_to_rust(
                                    &field_type_non_streaming,
                                    pkg.lookup(),
                                );
                                if union_contains_class(&field_type_non_streaming, class_name) {
                                    ty.meta_mut().make_boxed();
                                }
                                ty
                            } else {
                                // Fallback to String if field not found
                                r#type::TypeRust::String(
                                    None,
                                    r#type::TypeMetaRust {
                                        type_wrapper: r#type::TypeWrapper::None,
                                        wrap_stream_state: false,
                                    },
                                )
                            };

                            if rust_type.is_class_named(class_name) {
                                rust_type.make_boxed();
                            }

                            generated_types::FieldRust {
                                name: field.name,
                                original_name: field.original_name,
                                docstring: None,
                                rust_type,
                                pkg: &pkg,
                            }
                        })
                        .collect(),
                    dynamic: false, // TODO: Determine from class metadata
                    pkg: &pkg,
                }
            })
            .collect();
        let enums: Vec<generated_types::EnumRust> = ir
            .walk_enums()
            .map(|e| {
                let enum_data = ir_to_rust::enums::ir_enum_to_rust(e.item, &pkg);
                generated_types::EnumRust {
                    name: enum_data.name,
                    docstring: None, // TODO: Extract docstring from enum
                    values: enum_data.values,
                    dynamic: false, // TODO: Determine from enum metadata
                    pkg: &pkg,
                }
            })
            .collect();
        let unions: Vec<generated_types::UnionRust> = {
            let mut unions = ir
                .walk_all_non_streaming_unions()
                .filter_map(|t| {
                    ir_to_rust::unions::ir_union_to_rust(&t, &pkg).map(|union_data| {
                        generated_types::UnionRust {
                            name: union_data.name,
                            docstring: None, // TODO: Extract docstring from union
                            variants: union_data
                                .variants
                                .into_iter()
                                .map(|variant| generated_types::UnionVariantRust {
                                    name: variant.name,
                                    docstring: variant.docstring,
                                    rust_type: variant.rust_type,
                                    literal_value: variant.literal_value,
                                    literal_kind: variant.literal_kind,
                                    discriminators: variant.discriminators,
                                })
                                .collect(),
                            pkg: &pkg,
                            has_discriminators: union_data.has_discriminators,
                        }
                    })
                })
                .collect::<Vec<_>>();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        let mut type_aliases: Vec<generated_types::TypeAliasRust> = ir
            .walk_type_aliases()
            .map(|alias| ir_to_rust::type_aliases::ir_type_alias_to_rust(alias.item, &pkg))
            .collect();
        type_aliases.sort_by(|a, b| a.name.cmp(&b.name));
        type_aliases.dedup_by(|a, b| a.name == b.name);

        let stream_pkg = package::CurrentRenderPackage::new("stream_state", ir.clone());
        let mut stream_type_aliases: Vec<generated_types::TypeAliasRust> = ir
            .walk_type_aliases()
            .map(|alias| {
                ir_to_rust::type_aliases::ir_type_alias_to_rust_stream(alias.item, &stream_pkg)
            })
            .collect();
        stream_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));
        stream_type_aliases.dedup_by(|a, b| a.name == b.name);

        let mut stream_state_content =
            String::from("pub use baml_client_rust::StreamState;\npub use crate::types::*;\n\n");
        stream_state_content.push_str(&generated_types::render_rust_types(
            &stream_type_aliases,
            &stream_pkg,
        )?);
        collector.add_file("src/stream_state.rs", stream_state_content)?;
        collector.add_file(
            "src/types.rs",
            generated_types::render_all_rust_types(
                &rust_classes,
                &enums,
                &unions,
                &type_aliases,
                &pkg,
            )?,
        )?;

        Ok(())
    }
}

fn render_lib_rs(pkg: &package::CurrentRenderPackage) -> Result<String, anyhow::Error> {
    use askama::Template;

    #[derive(askama::Template)]
    #[template(path = "lib.rs.j2", escape = "none")]
    struct LibRs<'a> {
        crate_name: &'a str,
        baml_version: &'a str,
        pkg: &'a package::CurrentRenderPackage,
    }

    LibRs {
        crate_name: "baml_client",
        baml_version: "0.1.0", // TODO: Get actual BAML version
        pkg,
    }
    .render()
    .map_err(|e| anyhow::anyhow!("Template error: {}", e))
}

impl RustLanguageFeatures {
    fn generation_timestamp(&self) -> &str {
        use std::time::SystemTime;

        self.generation_timestamp
            .get_or_init(|| format!("{:?}", SystemTime::now()))
            .as_str()
    }

    fn render_cargo_toml(&self) -> Result<String, anyhow::Error> {
        use askama::Template;

        #[derive(askama::Template)]
        #[template(path = "cargo.toml.j2", escape = "none")]
        struct CargoToml {
            package_name: &'static str,
            lib_name: &'static str,
            version: &'static str,
            baml_version: &'static str,
            baml_client_version: &'static str,
            generation_timestamp: String,
        }

        CargoToml {
            package_name: "baml-client",
            lib_name: "baml_client",
            version: "0.1.0",
            baml_version: "0.1.0", // TODO: Get actual BAML version
            baml_client_version: "0.1.0",
            generation_timestamp: self.generation_timestamp().to_string(),
        }
        .render()
        .map_err(|e| anyhow::anyhow!("Template error: {}", e))
    }
}

#[cfg(test)]
mod rust_tests {
    use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};

    impl TestLanguageFeatures for crate::RustLanguageFeatures {
        fn test_name() -> &'static str {
            "rust"
        }
    }
    create_code_gen_test_suites!(crate::RustLanguageFeatures);
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_name() {
        use dir_writer::LanguageFeatures;
        use std::str::FromStr;

        let gen_type =
            baml_types::GeneratorOutputType::from_str(crate::RustLanguageFeatures::name())
                .expect("RustLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Rust);
    }
}
