// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllNullable {
    pub nullString: String,

    pub nullInt: String,

    pub nullFloat: String,

    pub nullBool: String,

    pub nullArray: String,

    pub nullObject: String,
}

impl AllNullable {
    /// Create a new AllNullable instance
    pub fn new(
        nullString: String,
        nullInt: String,
        nullFloat: String,
        nullBool: String,
        nullArray: String,
        nullObject: String,
    ) -> Self {
        Self {
            nullString,
            nullInt,
            nullFloat,
            nullBool,
            nullArray,
            nullObject,
        }
    }
}

impl Default for AllNullable {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for AllNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("nullString".to_string(), self.nullString.to_baml_value()?);
        map.insert("nullInt".to_string(), self.nullInt.to_baml_value()?);
        map.insert("nullFloat".to_string(), self.nullFloat.to_baml_value()?);
        map.insert("nullBool".to_string(), self.nullBool.to_baml_value()?);
        map.insert("nullArray".to_string(), self.nullArray.to_baml_value()?);
        map.insert("nullObject".to_string(), self.nullObject.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "AllNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for AllNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let nullString = map
                    .get("nullString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullString' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullInt = map
                    .get("nullInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullInt' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullFloat = map
                    .get("nullFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullFloat' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullBool = map
                    .get("nullBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullBool' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullArray = map
                    .get("nullArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullArray' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullObject = map
                    .get("nullObject")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullObject' in AllNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    nullString, nullInt, nullFloat, nullBool, nullArray, nullObject,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BooleanEdgeCases {
    pub explicitTrue: String,

    pub explicitFalse: String,

    pub arrayOfTrue: String,

    pub arrayOfFalse: String,

    pub mixedBoolArray: String,
}

impl BooleanEdgeCases {
    /// Create a new BooleanEdgeCases instance
    pub fn new(
        explicitTrue: String,
        explicitFalse: String,
        arrayOfTrue: String,
        arrayOfFalse: String,
        mixedBoolArray: String,
    ) -> Self {
        Self {
            explicitTrue,
            explicitFalse,
            arrayOfTrue,
            arrayOfFalse,
            mixedBoolArray,
        }
    }
}

impl Default for BooleanEdgeCases {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for BooleanEdgeCases {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "explicitTrue".to_string(),
            self.explicitTrue.to_baml_value()?,
        );
        map.insert(
            "explicitFalse".to_string(),
            self.explicitFalse.to_baml_value()?,
        );
        map.insert("arrayOfTrue".to_string(), self.arrayOfTrue.to_baml_value()?);
        map.insert(
            "arrayOfFalse".to_string(),
            self.arrayOfFalse.to_baml_value()?,
        );
        map.insert(
            "mixedBoolArray".to_string(),
            self.mixedBoolArray.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "BooleanEdgeCases".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for BooleanEdgeCases {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let explicitTrue = map
                    .get("explicitTrue")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'explicitTrue' in BooleanEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let explicitFalse = map
                    .get("explicitFalse")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'explicitFalse' in BooleanEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let arrayOfTrue = map
                    .get("arrayOfTrue")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'arrayOfTrue' in BooleanEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let arrayOfFalse = map
                    .get("arrayOfFalse")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'arrayOfFalse' in BooleanEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mixedBoolArray = map
                    .get("mixedBoolArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mixedBoolArray' in BooleanEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    explicitTrue,
                    explicitFalse,
                    arrayOfTrue,
                    arrayOfFalse,
                    mixedBoolArray,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircularReference {
    pub id: String,

    pub name: String,

    pub parent: String,

    pub children: String,

    pub relatedItems: String,
}

impl CircularReference {
    /// Create a new CircularReference instance
    pub fn new(
        id: String,
        name: String,
        parent: String,
        children: String,
        relatedItems: String,
    ) -> Self {
        Self {
            id,
            name,
            parent,
            children,
            relatedItems,
        }
    }
}

impl Default for CircularReference {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for CircularReference {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("parent".to_string(), self.parent.to_baml_value()?);
        map.insert("children".to_string(), self.children.to_baml_value()?);
        map.insert(
            "relatedItems".to_string(),
            self.relatedItems.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "CircularReference".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for CircularReference {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in CircularReference"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in CircularReference"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let parent = map
                    .get("parent")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'parent' in CircularReference"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let children = map
                    .get("children")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'children' in CircularReference"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let relatedItems = map
                    .get("relatedItems")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'relatedItems' in CircularReference"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, parent, children, relatedItems))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeepRecursion {
    pub value: String,

    pub next: String,
}

impl DeepRecursion {
    /// Create a new DeepRecursion instance
    pub fn new(value: String, next: String) -> Self {
        Self { value, next }
    }
}

impl Default for DeepRecursion {
    fn default() -> Self {
        Self::new(String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for DeepRecursion {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("value".to_string(), self.value.to_baml_value()?);
        map.insert("next".to_string(), self.next.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "DeepRecursion".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for DeepRecursion {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let value = map
                    .get("value")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'value' in DeepRecursion"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let next = map
                    .get("next")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'next' in DeepRecursion"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(value, next))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmptyCollections {
    pub emptyStringArray: String,

    pub emptyIntArray: String,

    pub emptyObjectArray: String,

    pub emptyMap: String,

    pub emptyNestedArray: String,
}

impl EmptyCollections {
    /// Create a new EmptyCollections instance
    pub fn new(
        emptyStringArray: String,
        emptyIntArray: String,
        emptyObjectArray: String,
        emptyMap: String,
        emptyNestedArray: String,
    ) -> Self {
        Self {
            emptyStringArray,
            emptyIntArray,
            emptyObjectArray,
            emptyMap,
            emptyNestedArray,
        }
    }
}

impl Default for EmptyCollections {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for EmptyCollections {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "emptyStringArray".to_string(),
            self.emptyStringArray.to_baml_value()?,
        );
        map.insert(
            "emptyIntArray".to_string(),
            self.emptyIntArray.to_baml_value()?,
        );
        map.insert(
            "emptyObjectArray".to_string(),
            self.emptyObjectArray.to_baml_value()?,
        );
        map.insert("emptyMap".to_string(), self.emptyMap.to_baml_value()?);
        map.insert(
            "emptyNestedArray".to_string(),
            self.emptyNestedArray.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "EmptyCollections".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for EmptyCollections {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let emptyStringArray = map
                    .get("emptyStringArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyStringArray' in EmptyCollections"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let emptyIntArray = map
                    .get("emptyIntArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyIntArray' in EmptyCollections"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let emptyObjectArray = map
                    .get("emptyObjectArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyObjectArray' in EmptyCollections"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let emptyMap = map
                    .get("emptyMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyMap' in EmptyCollections"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let emptyNestedArray = map
                    .get("emptyNestedArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyNestedArray' in EmptyCollections"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    emptyStringArray,
                    emptyIntArray,
                    emptyObjectArray,
                    emptyMap,
                    emptyNestedArray,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InnerNullable {
    pub value: String,
}

impl InnerNullable {
    /// Create a new InnerNullable instance
    pub fn new(value: String) -> Self {
        Self { value }
    }
}

impl Default for InnerNullable {
    fn default() -> Self {
        Self::new(String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for InnerNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("value".to_string(), self.value.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "InnerNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for InnerNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let value = map
                    .get("value")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'value' in InnerNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(value))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LargeStructure {
    pub field1: String,

    pub field2: String,

    pub field3: String,

    pub field4: String,

    pub field5: String,

    pub field6: String,

    pub field7: String,

    pub field8: String,

    pub field9: String,

    pub field10: String,

    pub field11: String,

    pub field12: String,

    pub field13: String,

    pub field14: String,

    pub field15: String,

    pub field16: String,

    pub field17: String,

    pub field18: String,

    pub field19: String,

    pub field20: String,

    pub array1: String,

    pub array2: String,

    pub array3: String,

    pub array4: String,

    pub array5: String,

    pub map1: String,

    pub map2: String,

    pub map3: String,

    pub map4: String,

    pub map5: String,
}

impl LargeStructure {
    /// Create a new LargeStructure instance
    pub fn new(
        field1: String,
        field2: String,
        field3: String,
        field4: String,
        field5: String,
        field6: String,
        field7: String,
        field8: String,
        field9: String,
        field10: String,
        field11: String,
        field12: String,
        field13: String,
        field14: String,
        field15: String,
        field16: String,
        field17: String,
        field18: String,
        field19: String,
        field20: String,
        array1: String,
        array2: String,
        array3: String,
        array4: String,
        array5: String,
        map1: String,
        map2: String,
        map3: String,
        map4: String,
        map5: String,
    ) -> Self {
        Self {
            field1,
            field2,
            field3,
            field4,
            field5,
            field6,
            field7,
            field8,
            field9,
            field10,
            field11,
            field12,
            field13,
            field14,
            field15,
            field16,
            field17,
            field18,
            field19,
            field20,
            array1,
            array2,
            array3,
            array4,
            array5,
            map1,
            map2,
            map3,
            map4,
            map5,
        }
    }
}

impl Default for LargeStructure {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for LargeStructure {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("field1".to_string(), self.field1.to_baml_value()?);
        map.insert("field2".to_string(), self.field2.to_baml_value()?);
        map.insert("field3".to_string(), self.field3.to_baml_value()?);
        map.insert("field4".to_string(), self.field4.to_baml_value()?);
        map.insert("field5".to_string(), self.field5.to_baml_value()?);
        map.insert("field6".to_string(), self.field6.to_baml_value()?);
        map.insert("field7".to_string(), self.field7.to_baml_value()?);
        map.insert("field8".to_string(), self.field8.to_baml_value()?);
        map.insert("field9".to_string(), self.field9.to_baml_value()?);
        map.insert("field10".to_string(), self.field10.to_baml_value()?);
        map.insert("field11".to_string(), self.field11.to_baml_value()?);
        map.insert("field12".to_string(), self.field12.to_baml_value()?);
        map.insert("field13".to_string(), self.field13.to_baml_value()?);
        map.insert("field14".to_string(), self.field14.to_baml_value()?);
        map.insert("field15".to_string(), self.field15.to_baml_value()?);
        map.insert("field16".to_string(), self.field16.to_baml_value()?);
        map.insert("field17".to_string(), self.field17.to_baml_value()?);
        map.insert("field18".to_string(), self.field18.to_baml_value()?);
        map.insert("field19".to_string(), self.field19.to_baml_value()?);
        map.insert("field20".to_string(), self.field20.to_baml_value()?);
        map.insert("array1".to_string(), self.array1.to_baml_value()?);
        map.insert("array2".to_string(), self.array2.to_baml_value()?);
        map.insert("array3".to_string(), self.array3.to_baml_value()?);
        map.insert("array4".to_string(), self.array4.to_baml_value()?);
        map.insert("array5".to_string(), self.array5.to_baml_value()?);
        map.insert("map1".to_string(), self.map1.to_baml_value()?);
        map.insert("map2".to_string(), self.map2.to_baml_value()?);
        map.insert("map3".to_string(), self.map3.to_baml_value()?);
        map.insert("map4".to_string(), self.map4.to_baml_value()?);
        map.insert("map5".to_string(), self.map5.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "LargeStructure".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for LargeStructure {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let field1 = map
                    .get("field1")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field1' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field2 = map
                    .get("field2")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field2' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field3 = map
                    .get("field3")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field3' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field4 = map
                    .get("field4")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field4' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field5 = map
                    .get("field5")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field5' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field6 = map
                    .get("field6")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field6' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field7 = map
                    .get("field7")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field7' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field8 = map
                    .get("field8")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field8' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field9 = map
                    .get("field9")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field9' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field10 = map
                    .get("field10")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field10' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field11 = map
                    .get("field11")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field11' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field12 = map
                    .get("field12")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field12' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field13 = map
                    .get("field13")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field13' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field14 = map
                    .get("field14")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field14' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field15 = map
                    .get("field15")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field15' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field16 = map
                    .get("field16")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field16' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field17 = map
                    .get("field17")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field17' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field18 = map
                    .get("field18")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field18' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field19 = map
                    .get("field19")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field19' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let field20 = map
                    .get("field20")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'field20' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let array1 = map
                    .get("array1")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'array1' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let array2 = map
                    .get("array2")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'array2' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let array3 = map
                    .get("array3")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'array3' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let array4 = map
                    .get("array4")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'array4' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let array5 = map
                    .get("array5")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'array5' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let map1 = map
                    .get("map1")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'map1' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let map2 = map
                    .get("map2")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'map2' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let map3 = map
                    .get("map3")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'map3' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let map4 = map
                    .get("map4")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'map4' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let map5 = map
                    .get("map5")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'map5' in LargeStructure"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    field1, field2, field3, field4, field5, field6, field7, field8, field9,
                    field10, field11, field12, field13, field14, field15, field16, field17,
                    field18, field19, field20, array1, array2, array3, array4, array5, map1, map2,
                    map3, map4, map5,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MixedEdgeCases {
    pub emptyString: String,

    pub singleChar: String,

    pub veryLongArray: String,

    pub deeplyNestedMap: String,

    pub mixedTypeArray: String,

    pub optionalEverything: String,
}

impl MixedEdgeCases {
    /// Create a new MixedEdgeCases instance
    pub fn new(
        emptyString: String,
        singleChar: String,
        veryLongArray: String,
        deeplyNestedMap: String,
        mixedTypeArray: String,
        optionalEverything: String,
    ) -> Self {
        Self {
            emptyString,
            singleChar,
            veryLongArray,
            deeplyNestedMap,
            mixedTypeArray,
            optionalEverything,
        }
    }
}

impl Default for MixedEdgeCases {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedEdgeCases {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("emptyString".to_string(), self.emptyString.to_baml_value()?);
        map.insert("singleChar".to_string(), self.singleChar.to_baml_value()?);
        map.insert(
            "veryLongArray".to_string(),
            self.veryLongArray.to_baml_value()?,
        );
        map.insert(
            "deeplyNestedMap".to_string(),
            self.deeplyNestedMap.to_baml_value()?,
        );
        map.insert(
            "mixedTypeArray".to_string(),
            self.mixedTypeArray.to_baml_value()?,
        );
        map.insert(
            "optionalEverything".to_string(),
            self.optionalEverything.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedEdgeCases".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedEdgeCases {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let emptyString = map
                    .get("emptyString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'emptyString' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let singleChar = map
                    .get("singleChar")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'singleChar' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let veryLongArray = map
                    .get("veryLongArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'veryLongArray' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let deeplyNestedMap = map
                    .get("deeplyNestedMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'deeplyNestedMap' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mixedTypeArray = map
                    .get("mixedTypeArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mixedTypeArray' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalEverything = map
                    .get("optionalEverything")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalEverything' in MixedEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    emptyString,
                    singleChar,
                    veryLongArray,
                    deeplyNestedMap,
                    mixedTypeArray,
                    optionalEverything,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NestedNullable {
    pub outer: String,
}

impl NestedNullable {
    /// Create a new NestedNullable instance
    pub fn new(outer: String) -> Self {
        Self { outer }
    }
}

impl Default for NestedNullable {
    fn default() -> Self {
        Self::new(String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NestedNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("outer".to_string(), self.outer.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "NestedNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NestedNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let outer = map
                    .get("outer")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'outer' in NestedNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(outer))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NullEdgeCases {
    pub allNull: String,

    pub someNull: String,

    pub nestedNull: String,
}

impl NullEdgeCases {
    /// Create a new NullEdgeCases instance
    pub fn new(allNull: String, someNull: String, nestedNull: String) -> Self {
        Self {
            allNull,
            someNull,
            nestedNull,
        }
    }
}

impl Default for NullEdgeCases {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NullEdgeCases {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("allNull".to_string(), self.allNull.to_baml_value()?);
        map.insert("someNull".to_string(), self.someNull.to_baml_value()?);
        map.insert("nestedNull".to_string(), self.nestedNull.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "NullEdgeCases".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NullEdgeCases {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let allNull = map
                    .get("allNull")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'allNull' in NullEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let someNull = map
                    .get("someNull")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'someNull' in NullEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nestedNull = map
                    .get("nestedNull")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nestedNull' in NullEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(allNull, someNull, nestedNull))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NumberEdgeCases {
    pub zero: String,

    pub negativeInt: String,

    pub largeInt: String,

    pub veryLargeInt: String,

    pub smallFloat: String,

    pub largeFloat: String,

    pub negativeFloat: String,

    pub scientificNotation: String,

    pub infinity: String,

    pub notANumber: String,
}

impl NumberEdgeCases {
    /// Create a new NumberEdgeCases instance
    pub fn new(
        zero: String,
        negativeInt: String,
        largeInt: String,
        veryLargeInt: String,
        smallFloat: String,
        largeFloat: String,
        negativeFloat: String,
        scientificNotation: String,
        infinity: String,
        notANumber: String,
    ) -> Self {
        Self {
            zero,
            negativeInt,
            largeInt,
            veryLargeInt,
            smallFloat,
            largeFloat,
            negativeFloat,
            scientificNotation,
            infinity,
            notANumber,
        }
    }
}

impl Default for NumberEdgeCases {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NumberEdgeCases {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("zero".to_string(), self.zero.to_baml_value()?);
        map.insert("negativeInt".to_string(), self.negativeInt.to_baml_value()?);
        map.insert("largeInt".to_string(), self.largeInt.to_baml_value()?);
        map.insert(
            "veryLargeInt".to_string(),
            self.veryLargeInt.to_baml_value()?,
        );
        map.insert("smallFloat".to_string(), self.smallFloat.to_baml_value()?);
        map.insert("largeFloat".to_string(), self.largeFloat.to_baml_value()?);
        map.insert(
            "negativeFloat".to_string(),
            self.negativeFloat.to_baml_value()?,
        );
        map.insert(
            "scientificNotation".to_string(),
            self.scientificNotation.to_baml_value()?,
        );
        map.insert("infinity".to_string(), self.infinity.to_baml_value()?);
        map.insert("notANumber".to_string(), self.notANumber.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "NumberEdgeCases".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NumberEdgeCases {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let zero = map
                    .get("zero")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'zero' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let negativeInt = map
                    .get("negativeInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'negativeInt' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let largeInt = map
                    .get("largeInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'largeInt' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let veryLargeInt = map
                    .get("veryLargeInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'veryLargeInt' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let smallFloat = map
                    .get("smallFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'smallFloat' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let largeFloat = map
                    .get("largeFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'largeFloat' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let negativeFloat = map
                    .get("negativeFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'negativeFloat' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let scientificNotation = map
                    .get("scientificNotation")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'scientificNotation' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let infinity = map
                    .get("infinity")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'infinity' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let notANumber = map
                    .get("notANumber")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'notANumber' in NumberEdgeCases"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    zero,
                    negativeInt,
                    largeInt,
                    veryLargeInt,
                    smallFloat,
                    largeFloat,
                    negativeFloat,
                    scientificNotation,
                    infinity,
                    notANumber,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptionalEverything {
    pub optString: String,

    pub optInt: String,

    pub optFloat: String,

    pub optBool: String,

    pub optArray: String,

    pub optMap: String,

    pub optObject: String,
}

impl OptionalEverything {
    /// Create a new OptionalEverything instance
    pub fn new(
        optString: String,
        optInt: String,
        optFloat: String,
        optBool: String,
        optArray: String,
        optMap: String,
        optObject: String,
    ) -> Self {
        Self {
            optString,
            optInt,
            optFloat,
            optBool,
            optArray,
            optMap,
            optObject,
        }
    }
}

impl Default for OptionalEverything {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalEverything {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("optString".to_string(), self.optString.to_baml_value()?);
        map.insert("optInt".to_string(), self.optInt.to_baml_value()?);
        map.insert("optFloat".to_string(), self.optFloat.to_baml_value()?);
        map.insert("optBool".to_string(), self.optBool.to_baml_value()?);
        map.insert("optArray".to_string(), self.optArray.to_baml_value()?);
        map.insert("optMap".to_string(), self.optMap.to_baml_value()?);
        map.insert("optObject".to_string(), self.optObject.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalEverything".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalEverything {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let optString = map
                    .get("optString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optString' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optInt = map
                    .get("optInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optInt' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optFloat = map
                    .get("optFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optFloat' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optBool = map
                    .get("optBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optBool' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optArray = map
                    .get("optArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optArray' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optMap = map
                    .get("optMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optMap' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optObject = map
                    .get("optObject")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optObject' in OptionalEverything"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    optString, optInt, optFloat, optBool, optArray, optMap, optObject,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OuterNullable {
    pub inner: String,
}

impl OuterNullable {
    /// Create a new OuterNullable instance
    pub fn new(inner: String) -> Self {
        Self { inner }
    }
}

impl Default for OuterNullable {
    fn default() -> Self {
        Self::new(String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OuterNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("inner".to_string(), self.inner.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OuterNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OuterNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let inner = map
                    .get("inner")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'inner' in OuterNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(inner))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SomeNullable {
    pub presentString: String,

    pub nullString: String,

    pub presentInt: String,

    pub nullInt: String,
}

impl SomeNullable {
    /// Create a new SomeNullable instance
    pub fn new(
        presentString: String,
        nullString: String,
        presentInt: String,
        nullInt: String,
    ) -> Self {
        Self {
            presentString,
            nullString,
            presentInt,
            nullInt,
        }
    }
}

impl Default for SomeNullable {
    fn default() -> Self {
        Self::new(String::new(), String::new(), String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for SomeNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "presentString".to_string(),
            self.presentString.to_baml_value()?,
        );
        map.insert("nullString".to_string(), self.nullString.to_baml_value()?);
        map.insert("presentInt".to_string(), self.presentInt.to_baml_value()?);
        map.insert("nullInt".to_string(), self.nullInt.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "SomeNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for SomeNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let presentString = map
                    .get("presentString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'presentString' in SomeNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullString = map
                    .get("nullString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullString' in SomeNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let presentInt = map
                    .get("presentInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'presentInt' in SomeNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullInt = map
                    .get("nullInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullInt' in SomeNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(presentString, nullString, presentInt, nullInt))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecialCharacters {
    pub normalText: String,

    pub withNewlines: String,

    pub withTabs: String,

    pub withQuotes: String,

    pub withBackslashes: String,

    pub withUnicode: String,

    pub withEmoji: String,

    pub withMixedSpecial: String,
}

impl SpecialCharacters {
    /// Create a new SpecialCharacters instance
    pub fn new(
        normalText: String,
        withNewlines: String,
        withTabs: String,
        withQuotes: String,
        withBackslashes: String,
        withUnicode: String,
        withEmoji: String,
        withMixedSpecial: String,
    ) -> Self {
        Self {
            normalText,
            withNewlines,
            withTabs,
            withQuotes,
            withBackslashes,
            withUnicode,
            withEmoji,
            withMixedSpecial,
        }
    }
}

impl Default for SpecialCharacters {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for SpecialCharacters {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("normalText".to_string(), self.normalText.to_baml_value()?);
        map.insert(
            "withNewlines".to_string(),
            self.withNewlines.to_baml_value()?,
        );
        map.insert("withTabs".to_string(), self.withTabs.to_baml_value()?);
        map.insert("withQuotes".to_string(), self.withQuotes.to_baml_value()?);
        map.insert(
            "withBackslashes".to_string(),
            self.withBackslashes.to_baml_value()?,
        );
        map.insert("withUnicode".to_string(), self.withUnicode.to_baml_value()?);
        map.insert("withEmoji".to_string(), self.withEmoji.to_baml_value()?);
        map.insert(
            "withMixedSpecial".to_string(),
            self.withMixedSpecial.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "SpecialCharacters".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for SpecialCharacters {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let normalText = map
                    .get("normalText")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'normalText' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withNewlines = map
                    .get("withNewlines")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withNewlines' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withTabs = map
                    .get("withTabs")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withTabs' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withQuotes = map
                    .get("withQuotes")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withQuotes' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withBackslashes = map
                    .get("withBackslashes")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withBackslashes' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withUnicode = map
                    .get("withUnicode")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withUnicode' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withEmoji = map
                    .get("withEmoji")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withEmoji' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let withMixedSpecial = map
                    .get("withMixedSpecial")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'withMixedSpecial' in SpecialCharacters"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    normalText,
                    withNewlines,
                    withTabs,
                    withQuotes,
                    withBackslashes,
                    withUnicode,
                    withEmoji,
                    withMixedSpecial,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub id: String,

    pub name: String,
}

impl User {
    /// Create a new User instance
    pub fn new(id: String, name: String) -> Self {
        Self { id, name }
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new(String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for User {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "User".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for User {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VeryLongStrings {
    pub shortString: String,

    pub mediumString: String,

    pub longString: String,

    pub veryLongString: String,

    pub extremelyLongString: String,
}

impl VeryLongStrings {
    /// Create a new VeryLongStrings instance
    pub fn new(
        shortString: String,
        mediumString: String,
        longString: String,
        veryLongString: String,
        extremelyLongString: String,
    ) -> Self {
        Self {
            shortString,
            mediumString,
            longString,
            veryLongString,
            extremelyLongString,
        }
    }
}

impl Default for VeryLongStrings {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for VeryLongStrings {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("shortString".to_string(), self.shortString.to_baml_value()?);
        map.insert(
            "mediumString".to_string(),
            self.mediumString.to_baml_value()?,
        );
        map.insert("longString".to_string(), self.longString.to_baml_value()?);
        map.insert(
            "veryLongString".to_string(),
            self.veryLongString.to_baml_value()?,
        );
        map.insert(
            "extremelyLongString".to_string(),
            self.extremelyLongString.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "VeryLongStrings".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for VeryLongStrings {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let shortString = map
                    .get("shortString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'shortString' in VeryLongStrings"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mediumString = map
                    .get("mediumString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mediumString' in VeryLongStrings"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let longString = map
                    .get("longString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'longString' in VeryLongStrings"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let veryLongString = map
                    .get("veryLongString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'veryLongString' in VeryLongStrings"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let extremelyLongString = map
                    .get("extremelyLongString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'extremelyLongString' in VeryLongStrings"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    shortString,
                    mediumString,
                    longString,
                    veryLongString,
                    extremelyLongString,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3BoolOrIntOrString {
    String(String),
    Int(i64),
    Bool(bool),
}

impl Union3BoolOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union3BoolOrIntOrString
impl Union3BoolOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3BoolOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}
