# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.
import typing

from pydantic import BaseModel



StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing.Literal["Pending", "Incomplete", "Complete"]

# #########################################################################
# Generated classes (1)
# #########################################################################

class UseMyUnion(BaseModel):
    u: typing.Optional[typing.Union[int, typing.List[typing.Optional["Recursive1"]], str]] = None

# #########################################################################
# Generated type aliases (5)
# #########################################################################


JSON = typing.Optional[typing.Union[str, int, float, typing.Dict[str, "JSON"], typing.List["JSON"]]]


MyUnion = typing.Optional[typing.Union["Recursive1", int, str]]


Recursive1 = typing.Optional[typing.Union[int, typing.List[typing.Optional["Recursive1"]]]]


Nonrecursive1 = typing.Optional[int]


Nonrecursive2 = typing.Optional[str]
