// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//
//	$ go install github.com/boundaryml/baml/baml-cli
package baml_client

import (
	"context"
	"enums/baml_client/types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() TFinal {
	return *s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() TStream {
	return *s.as_stream
}

// / Streaming version of FnTestAliasedEnumOutput
func (*stream) FnTestAliasedEnumOutput(ctx context.Context, input string, opts ...CallOptionFunc) <-chan StreamValue[*types.TestEnum, types.TestEnum] {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	channel := make(chan StreamValue[*types.TestEnum, types.TestEnum])
	raw, err := bamlRuntime.CallFunctionStream(ctx, "FnTestAliasedEnumOutput", encoded)
	if err != nil {
		close(channel)
		return channel
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-raw:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.TestEnum)
					channel <- StreamValue[*types.TestEnum, types.TestEnum]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := (result.StreamData).(*types.TestEnum)
					channel <- StreamValue[*types.TestEnum, types.TestEnum]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel
}
