// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use std::collections::HashMap;

pub fn baml_source_files() -> HashMap<&'static str, &'static str> {
    let mut map = HashMap::new();
    map.insert(
        "baml_src/main.baml",
        r###"class SimpleClass {
    digits int
    words string  @stream.with_state
}

function MakeSimpleClass() -> SimpleClass {
    client "openai/gpt-4o-mini"
    prompt #"
        {{ ctx.output_format }}
    "#
}

function ConsumeSimpleClass(item: SimpleClass) -> SimpleClass {
    client "openai/gpt-4o-mini"
    prompt #"
        Return back to me verbatim:

        {{ item }}
    "#
}

test MakeSimpleClassTest {
    functions [MakeSimpleClass]
    args {}
}
"###,
    );
    map
}
