# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Baml::TypeCoerce::CoercionError; end
module Baml::TypeCoerce::Converter; end
module Minitest::Reporters; end
module Minitest::Reporters::SpecReporter; end
module Minitest::Test; end
module Rake::DSL; end
module Rake::FileUtilsExt; end
module T::Struct::ActsAsComparable; end
