flowchart LR
  subgraph sg0["BasicSections"]
    direction LR
  subgraph sg1["Main Processing"]
    direction LR
  n2["Generate Summary"]
  subgraph sg3["Make Space"]
    direction LR
  n4["Prepare Final Output"]
  n5["Final Output"]
    n4 --> n5
  end
    n2 --> n4
  end
  end