flowchart LR
  subgraph sg0["Main Processing"]
    direction LR
  n1["Generate Summary"]
  subgraph sg2["Make Space"]
    direction LR
  n3["Prepare Final Output"]
  n4["Final Output"]
    n3 --> n4
  end
    n1 --> n3
  end