---
config:
  layout: elk
---

flowchart LR
  subgraph sg0["Start"]
    direction LR
    n0["After"]
  end
%%__BAML_SPANMAP__={"n0":{"file_path":"/Users/egor/Documents/boundary/baml-main/baml/engine/baml-lib/baml/tests/validation_files/headers/if_then_only_header.baml","start_line":6,"start":4,"end_line":7,"end":0}}
  click n0 call bamlMermaidNodeClick() "Go to source"