flowchart LR
  subgraph sg0["Parent"]
    direction LR
  n1["MD Child"]
  subgraph sg2["loop 1"]
    direction LR
  n3["Loop Child"]
  class n3 loopContainer;
  n4["And stuff"]
  class n4 loopContainer;
n3 --> n4
  end
n1 --> n3
  end