flowchart LR
  n0["Section One"]
  subgraph sg1["Section Two"]
    direction LR
  subgraph sg2["Subsection 2.1"]
    direction LR
  n3["Subsubsection 2.1.1"]
  end
  end
  n4["Section Three"]
n0 --> n3
n3 --> n4