flowchart LR
  subgraph sg0["NestedScopes"]
    direction LR
  n1["Top Level"]
  n3{"First Section"}
  class n3 decisionNode;
  subgraph sg2["First Section"]
    direction LR
  n4["Inside If Block"]
    n3 --> n4
  n5["Inside Else Block"]
    n3 --> n5
  end
n1 --> n3
  end