flowchart LR
  subgraph sg0["Top Level"]
    direction LR
  n2{"First Section"}
  class n2 decisionNode;
  subgraph sg1["First Section"]
    direction LR
  n3["Inside If Block"]
    n2 --> n3
  n4["Inside Else Block"]
    n2 --> n4
  end
  end