flowchart LR
  subgraph sg0["Main Function"]
    direction LR
  n2{"If statement 1"}
  class n2 decisionNode;
  subgraph sg1["If statement 1"]
    direction LR
  n4{"If statement 2.1"}
  class n4 decisionNode;
  subgraph sg3["If statement 2.1"]
    direction LR
  n6{"If statement 3.1"}
  class n6 decisionNode;
  subgraph sg5["If statement 3.1"]
    direction LR
  n7["True"]
    n6 --> n7
  n8["Third False"]
    n6 --> n8
  end
    n4 --> n6
  n10{"If statement 3.2"}
  class n10 decisionNode;
  subgraph sg9["If statement 3.2"]
    direction LR
  n11["True"]
    n10 --> n11
  n12["Third False"]
    n10 --> n12
  end
    n4 --> n10
  end
    n2 --> n4
  n14{"If statement 2.2"}
  class n14 decisionNode;
  subgraph sg13["If statement 2.2"]
    direction LR
  n16{"If statement 3.1"}
  class n16 decisionNode;
  subgraph sg15["If statement 3.1"]
    direction LR
  n17["True"]
    n16 --> n17
  n18["Third False"]
    n16 --> n18
  end
    n14 --> n16
  n20{"If statement 3.2"}
  class n20 decisionNode;
  subgraph sg19["If statement 3.2"]
    direction LR
  n21["True"]
    n20 --> n21
  n22["Third False"]
    n20 --> n22
  end
    n14 --> n20
  end
    n2 --> n14
  end
  end