---
config:
  layout: elk
---

flowchart LR
  subgraph sg0["Top Container"]
    direction LR
    n0["Only Child"]
  end
%%__BAML_SPANMAP__={"n0":{"file_path":"/Users/egor/Documents/boundary/baml-main/baml/engine/baml-lib/baml/tests/validation_files/headers/top_level_not_flattened.baml","start_line":2,"start":4,"end_line":3,"end":0}}
  click n0 call bamlMermaidNodeClick() "Go to source"