//! Basic integration tests for the BAML VM

use baml_vm::{
    bytecode::{Literal, VarId},
    compiler::{BinaryOp, Compiler, Expr, Stmt},
    VirtualMachine,
};

#[test]
fn test_simple_arithmetic() {
    // Create a simple program:
    // let x = 10
    // let y = 20
    // let z = x + y
    // print(z)
    
    let statements = vec![
        Stmt::Let {
            name: "x".to_string(),
            value: Expr::Literal(Literal::Int(10)),
        },
        Stmt::Let {
            name: "y".to_string(),
            value: Expr::Literal(Literal::Int(20)),
        },
        Stmt::Let {
            name: "z".to_string(),
            value: Expr::Binary {
                op: BinaryOp::Add,
                left: Box::new(Expr::Variable("x".to_string())),
                right: Box::new(Expr::Variable("y".to_string())),
            },
        },
        Stmt::Print(Expr::Variable("z".to_string())),
        Stmt::Return(Some(Expr::Variable("z".to_string()))),
    ];
    
    // Compile the program
    let mut compiler = Compiler::new();
    let program = compiler.compile_simple(statements).unwrap();
    
    // Debug: Print the generated bytecode
    println!("Generated bytecode:");
    for func in &program.functions {
        println!("Function {}: ", func.name);
        for block in &func.blocks {
            println!("  Block {:?}:", block.id);
            for inst in &block.instructions {
                println!("    {:?}", inst);
            }
        }
    }
    
    // Execute the program
    let mut vm = VirtualMachine::new(program).unwrap();
    let result = vm.execute().unwrap();
    
    // Check result
    assert_eq!(result, Some(baml_vm::Value::Int(30)));
}

#[test]
fn test_if_expression() {
    // Create a program with if expression:
    // let x = 10
    // let y = if x < 20 { 100 } else { 200 }
    // return y
    
    let statements = vec![
        Stmt::Let {
            name: "x".to_string(),
            value: Expr::Literal(Literal::Int(10)),
        },
        Stmt::Let {
            name: "y".to_string(),
            value: Expr::If {
                condition: Box::new(Expr::Binary {
                    op: BinaryOp::Lt,
                    left: Box::new(Expr::Variable("x".to_string())),
                    right: Box::new(Expr::Literal(Literal::Int(20))),
                }),
                then_branch: Box::new(Expr::Literal(Literal::Int(100))),
                else_branch: Some(Box::new(Expr::Literal(Literal::Int(200)))),
            },
        },
        Stmt::Return(Some(Expr::Variable("y".to_string()))),
    ];
    
    // Compile and execute
    let mut compiler = Compiler::new();
    let program = compiler.compile_simple(statements).unwrap();
    println!("Program: {}", program);
    let mut vm = VirtualMachine::new(program).unwrap();
    let result = vm.execute().unwrap();
    
    // Check result - should be 100 since 10 < 20
    assert_eq!(result, Some(baml_vm::Value::Int(100)));
}

#[test]
fn test_string_operations() {
    // Test string concatenation
    let statements = vec![
        Stmt::Let {
            name: "hello".to_string(),
            value: Expr::Literal(Literal::String("Hello, ".to_string())),
        },
        Stmt::Let {
            name: "world".to_string(),
            value: Expr::Literal(Literal::String("World!".to_string())),
        },
        Stmt::Let {
            name: "greeting".to_string(),
            value: Expr::Binary {
                op: BinaryOp::Add,
                left: Box::new(Expr::Variable("hello".to_string())),
                right: Box::new(Expr::Variable("world".to_string())),
            },
        },
        Stmt::Return(Some(Expr::Variable("greeting".to_string()))),
    ];
    
    let mut compiler = Compiler::new();
    let program = compiler.compile_simple(statements).unwrap();
    let mut vm = VirtualMachine::new(program).unwrap();
    let result = vm.execute().unwrap();
    
    assert_eq!(result, Some(baml_vm::Value::String("Hello, World!".to_string())));
} 