function simpleIf() -> string {
    let x = if (true) { "yes" } else { "no" };
    x
}

// function simpleIf() {
//   let x = if true {
//   
//     "yes"
//   } else {
//   
//     "no"
//   } ;
//
//   x
// }
//
// class std.Request {
//   base_url: string
//   headers: map<string, string>
//   query_params: map<string, string>
// }
//
// class baml.WatchOptions {
//   name: string
//   when: ("never" | "manual" | (ANY, ANY) -> bool)
// }
//
// enum std.HttpMethod {
//   Get
// }
