function nestedOps() -> int {
  let x = 1 + (2 + (3 + 4));

  x
}

// function nestedOps() {
//   let x = 1 + (2 + (3 + 4));
//
//   x
// }
//
// class std.Request {
//   base_url: string
//   headers: map<string, string>
//   query_params: map<string, string>
// }
//
// class baml.WatchOptions {
//   name: string
//   when: ("never" | "manual" | (ANY, ANY) -> bool)
// }
//
// enum std.HttpMethod {
//   Get
// }
