// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go install github.com/boundaryml/baml/go
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
package baml_client

import (
	"context"
	"os"
	"strings"

	"example.com/integ-tests/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

var bamlRuntime *baml.BamlRuntime

func init() {
	var env_vars = map[string]string{}
	for _, env_var := range os.Environ() {
		key, value, _ := strings.Cut(env_var, "=")
		env_vars[key] = value
	}
	baml.SetTypeMap(typeMap)
	runtime, err := baml.CreateRuntime("./baml_src", getBamlFiles(), env_vars)
	if err != nil {
		panic(err)
	}
	bamlRuntime = &runtime
}

type stream struct {}

var Stream = &stream{}

func castSlice[T any](result any, castResult func(any) T) []T {
	items := result.([]any)
	casted := make([]T, len(items))
	for i, item := range items {
		casted[i] = castResult(item)
	}
	return casted
}

func castOptional[T any](result any, castResult func(any) T) *T {
	if result == nil {
		return nil
	}
	val := castResult(result)
	return &val
}

