// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go install github.com/boundaryml/baml/go
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
package baml_client

var file_map = map[string]string{

}

func getBamlFiles() map[string]string {
  return file_map
}