// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::{source_map, types::*};
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let mut env_vars: std::collections::HashMap<String, String> = std::env::vars().collect();
        env_vars
            .entry("BAML_SRC".to_string())
            .or_insert_with(|| "./baml_src".to_string());

        // Prefer local baml_src during generated tests
        let mut last_error: Option<baml_client_rust::BamlError> = None;

        #[cfg(not(target_arch = "wasm32"))]
        {
            let local = std::path::Path::new("baml_src");
            if local.exists() {
                match CoreBamlClient::from_directory(local, env_vars.clone()) {
                    Ok(client) => return Ok(Self { client }),
                    Err(err) => {
                        #[cfg(debug_assertions)]
                        eprintln!("BamlClient::from_directory failed: {err}");
                        last_error = Some(err);
                    }
                }
            }
        }

        // Fall back to embedded source map
        let embedded_files: std::collections::HashMap<String, String> =
            source_map::baml_source_files()
                .into_iter()
                .map(|(path, contents)| (path.to_string(), contents.to_string()))
                .collect();
        if !embedded_files.is_empty() {
            match CoreBamlClient::from_file_content("./baml_src", &embedded_files, env_vars.clone())
            {
                Ok(client) => return Ok(Self { client }),
                Err(err) => {
                    #[cfg(debug_assertions)]
                    eprintln!("BamlClient::from_file_content failed: {err}");
                    last_error = Some(err);
                }
            }
        }

        let client = match CoreBamlClient::from_env() {
            Ok(client) => client,
            Err(err) => {
                #[cfg(debug_assertions)]
                if let Some(prev) = &last_error {
                    eprintln!("BamlClient::from_env failed after embedded attempts: {prev}");
                }
                return Err(err);
            }
        };
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// TestEmptyCollections - Generated BAML function
    pub async fn test_empty_collections(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::PrimitiveArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestEmptyCollections", context)
            .await
    }

    /// TestEmptyCollections (streaming) - Generated BAML function  
    pub async fn test_empty_collections_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::PrimitiveArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestEmptyCollections", context)
            .await
    }
}
impl BamlClient {
    /// TestMixedPrimitives - Generated BAML function
    pub async fn test_mixed_primitives(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::MixedPrimitives> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestMixedPrimitives", context)
            .await
    }

    /// TestMixedPrimitives (streaming) - Generated BAML function  
    pub async fn test_mixed_primitives_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::MixedPrimitives>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestMixedPrimitives", context)
            .await
    }
}
impl BamlClient {
    /// TestPrimitiveArrays - Generated BAML function
    pub async fn test_primitive_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::PrimitiveArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestPrimitiveArrays", context)
            .await
    }

    /// TestPrimitiveArrays (streaming) - Generated BAML function  
    pub async fn test_primitive_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::PrimitiveArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestPrimitiveArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestPrimitiveMaps - Generated BAML function
    pub async fn test_primitive_maps(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::PrimitiveMaps> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestPrimitiveMaps", context)
            .await
    }

    /// TestPrimitiveMaps (streaming) - Generated BAML function  
    pub async fn test_primitive_maps_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::PrimitiveMaps>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestPrimitiveMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestPrimitiveTypes - Generated BAML function
    pub async fn test_primitive_types(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::PrimitiveTypes> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestPrimitiveTypes", context)
            .await
    }

    /// TestPrimitiveTypes (streaming) - Generated BAML function  
    pub async fn test_primitive_types_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::PrimitiveTypes>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestPrimitiveTypes", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelBool - Generated BAML function
    pub async fn test_top_level_bool(&self, input: impl Into<String>) -> BamlResult<bool> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestTopLevelBool", context).await
    }

    /// TestTopLevelBool (streaming) - Generated BAML function  
    pub async fn test_top_level_bool_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<bool>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelBool", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelFloat - Generated BAML function
    pub async fn test_top_level_float(&self, input: impl Into<String>) -> BamlResult<f64> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelFloat", context)
            .await
    }

    /// TestTopLevelFloat (streaming) - Generated BAML function  
    pub async fn test_top_level_float_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<f64>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelFloat", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelInt - Generated BAML function
    pub async fn test_top_level_int(&self, input: impl Into<String>) -> BamlResult<i64> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestTopLevelInt", context).await
    }

    /// TestTopLevelInt (streaming) - Generated BAML function  
    pub async fn test_top_level_int_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<i64>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelInt", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelNull - Generated BAML function
    pub async fn test_top_level_null(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<serde_json::Value> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestTopLevelNull", context).await
    }

    /// TestTopLevelNull (streaming) - Generated BAML function  
    pub async fn test_top_level_null_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<serde_json::Value>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelNull", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelString - Generated BAML function
    pub async fn test_top_level_string(&self, input: impl Into<String>) -> BamlResult<String> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelString", context)
            .await
    }

    /// TestTopLevelString (streaming) - Generated BAML function  
    pub async fn test_top_level_string_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<String>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelString", context)
            .await
    }
}
