// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//
//	$ go install github.com/boundaryml/baml/baml-cli
package baml_client

import (
	"context"
	"sample/baml_client/types"

	"os"
	"strings"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

var bamlRuntime *baml.BamlRuntime

func getEnvVars(overrides map[string]string) map[string]string {
	var env = map[string]string{}
	for _, env_var := range os.Environ() {
		key, value, _ := strings.Cut(env_var, "=")
		env[key] = value
	}
	if overrides != nil {
		// Since go uses empty strings as zero values for string and not a `null` value, we unset env vars that are empty.
		for key, value := range overrides {
			if value != "" {
				env[key] = value
			} else {
				delete(env, key)
			}
		}
	}
	return env
}

func init() {
	baml.SetTypeMap(typeMap)
	runtime, err := baml.CreateRuntime("./baml_src", getBamlFiles(), getEnvVars(nil))
	if err != nil {
		panic(err)
	}
	bamlRuntime = &runtime
}

type stream struct{}

var Stream = &stream{}

func castOptional[T any](result any, castResult func(any) T) *T {
	if result == nil {
		return nil
	}
	val := castResult(result)
	return &val
}

type callOption struct {
	clientRegistry *baml.ClientRegistry
	env            map[string]string
}

type CallOptionFunc func(*callOption)

func WithClientRegistry(clientRegistry *baml.ClientRegistry) CallOptionFunc {
	return func(o *callOption) {
		o.clientRegistry = clientRegistry
	}
}

func WithEnv(env map[string]string) CallOptionFunc {
	return func(o *callOption) {
		o.env = env
	}
}

func Foo(ctx context.Context, x int, opts ...CallOptionFunc) (types.Union2IntOrString, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"x": x},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "Foo", encoded)
	if err != nil {
		return nil, err
	}

	if result.Error != nil {
		return nil, result.Error
	}

	castResult := func(result any) types.Union2IntOrString {
		return types.Union2IntOrString
	}

	casted := castResult(*result.Data)

	return casted, nil
}

/// Streaming version of Foo

func (*stream) Foo(ctx context.Context, x int, opts ...CallOptionFunc) <-chan StreamResult[*Union2IntOrString, types.Union2IntOrString] {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"x": x},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	channel := make(chan StreamResult[*Union2IntOrString, types.Union2IntOrString])
	raw, err := bamlRuntime.CallFunctionStream(ctx, "Foo", encoded)
	if err != nil {
		close(channel)
		return channel
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-raw:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				channel <- (*result.Data).(*Union2IntOrString)
			}
		}
	}()
	return channel
}
