// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UseMyUnion {
    pub u: String,
}

impl UseMyUnion {
    /// Create a new UseMyUnion instance
    pub fn new(u: String) -> Self {
        Self { u }
    }
}

impl Default for UseMyUnion {
    fn default() -> Self {
        Self::new(String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for UseMyUnion {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("u".to_string(), self.u.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "UseMyUnion".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for UseMyUnion {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let u = map
                    .get("u")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'u' in UseMyUnion"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(u))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union2IntOrListRecursive1 {
    Int(i64),
    List1(Vec<crate::types::Recursive1>),
}

impl Union2IntOrListRecursive1 {
    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2IntOrListRecursive1 with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a List1 variant
    pub fn is_list1(&self) -> bool {
        matches!(self, Self::List1(_))
    }
    /// Get the List1 value if this union contains it
    pub fn as_list1(&self) -> Option<&Vec<crate::types::Recursive1>> {
        match self {
            Self::List1(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the List1 value, consuming the union
    pub fn into_list1(self) -> Option<Vec<crate::types::Recursive1>> {
        match self {
            Self::List1(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the List1 value if this union contains it
    pub fn as_list1_mut(&mut self) -> Option<&mut Vec<crate::types::Recursive1>> {
        match self {
            Self::List1(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2IntOrListRecursive1 with a List1 variant
    pub fn list1(value: Vec<crate::types::Recursive1>) -> Self {
        Self::List1(value)
    }
}

/// Pattern matching helper for Union2IntOrListRecursive1
impl Union2IntOrListRecursive1 {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        int: impl FnOnce(&i64) -> T,
        list1: impl FnOnce(&Vec<crate::types::Recursive1>) -> T,
    ) -> T {
        match self {
            Self::Int(v) => int(v),
            Self::List1(v) => list1(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        int: impl FnOnce(i64) -> T,
        list1: impl FnOnce(Vec<crate::types::Recursive1>) -> T,
    ) -> T {
        match self {
            Self::Int(v) => int(v),
            Self::List1(v) => list1(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union2IntOrListRecursive1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::List1(v) => write!(f, "List1({:?})", v),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3IntOrRecursive1OrString {
    Recursive1(crate::types::Recursive1),
    Int(i64),
    String(String),
}

impl Union3IntOrRecursive1OrString {
    /// Check if this union is a Recursive1 variant
    pub fn is_recursive1(&self) -> bool {
        matches!(self, Self::Recursive1(_))
    }
    /// Get the Recursive1 value if this union contains it
    pub fn as_recursive1(&self) -> Option<&crate::types::Recursive1> {
        match self {
            Self::Recursive1(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Recursive1 value, consuming the union
    pub fn into_recursive1(self) -> Option<crate::types::Recursive1> {
        match self {
            Self::Recursive1(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Recursive1 value if this union contains it
    pub fn as_recursive1_mut(&mut self) -> Option<&mut crate::types::Recursive1> {
        match self {
            Self::Recursive1(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3IntOrRecursive1OrString with a Recursive1 variant
    pub fn recursive1(value: crate::types::Recursive1) -> Self {
        Self::Recursive1(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3IntOrRecursive1OrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3IntOrRecursive1OrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }
}

/// Pattern matching helper for Union3IntOrRecursive1OrString
impl Union3IntOrRecursive1OrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        recursive1: impl FnOnce(&crate::types::Recursive1) -> T,
        int: impl FnOnce(&i64) -> T,
        string: impl FnOnce(&String) -> T,
    ) -> T {
        match self {
            Self::Recursive1(v) => recursive1(v),
            Self::Int(v) => int(v),
            Self::String(v) => string(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        recursive1: impl FnOnce(crate::types::Recursive1) -> T,
        int: impl FnOnce(i64) -> T,
        string: impl FnOnce(String) -> T,
    ) -> T {
        match self {
            Self::Recursive1(v) => recursive1(v),
            Self::Int(v) => int(v),
            Self::String(v) => string(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3IntOrRecursive1OrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Recursive1(v) => write!(f, "Recursive1({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::String(v) => write!(f, "String({:?})", v),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString {
    String(String),
    Int(i64),
    Float(f64),
    Map3(std::collections::HashMap<String, crate::types::JSON>),
    List4(Vec<crate::types::JSON>),
}

impl Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Float variant
    pub fn is_float(&self) -> bool {
        matches!(self, Self::Float(_))
    }
    /// Get the Float value if this union contains it
    pub fn as_float(&self) -> Option<&f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Float value, consuming the union
    pub fn into_float(self) -> Option<f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Float value if this union contains it
    pub fn as_float_mut(&mut self) -> Option<&mut f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString with a Float variant
    pub fn float(value: f64) -> Self {
        Self::Float(value)
    }

    /// Check if this union is a Map3 variant
    pub fn is_map3(&self) -> bool {
        matches!(self, Self::Map3(_))
    }
    /// Get the Map3 value if this union contains it
    pub fn as_map3(&self) -> Option<&std::collections::HashMap<String, crate::types::JSON>> {
        match self {
            Self::Map3(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Map3 value, consuming the union
    pub fn into_map3(self) -> Option<std::collections::HashMap<String, crate::types::JSON>> {
        match self {
            Self::Map3(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Map3 value if this union contains it
    pub fn as_map3_mut(
        &mut self,
    ) -> Option<&mut std::collections::HashMap<String, crate::types::JSON>> {
        match self {
            Self::Map3(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString with a Map3 variant
    pub fn map3(value: std::collections::HashMap<String, crate::types::JSON>) -> Self {
        Self::Map3(value)
    }

    /// Check if this union is a List4 variant
    pub fn is_list4(&self) -> bool {
        matches!(self, Self::List4(_))
    }
    /// Get the List4 value if this union contains it
    pub fn as_list4(&self) -> Option<&Vec<crate::types::JSON>> {
        match self {
            Self::List4(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the List4 value, consuming the union
    pub fn into_list4(self) -> Option<Vec<crate::types::JSON>> {
        match self {
            Self::List4(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the List4 value if this union contains it
    pub fn as_list4_mut(&mut self) -> Option<&mut Vec<crate::types::JSON>> {
        match self {
            Self::List4(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString with a List4 variant
    pub fn list4(value: Vec<crate::types::JSON>) -> Self {
        Self::List4(value)
    }
}

/// Pattern matching helper for Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString
impl Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        float: impl FnOnce(&f64) -> T,
        map3: impl FnOnce(&std::collections::HashMap<String, crate::types::JSON>) -> T,
        list4: impl FnOnce(&Vec<crate::types::JSON>) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Map3(v) => map3(v),
            Self::List4(v) => list4(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        float: impl FnOnce(f64) -> T,
        map3: impl FnOnce(std::collections::HashMap<String, crate::types::JSON>) -> T,
        list4: impl FnOnce(Vec<crate::types::JSON>) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Map3(v) => map3(v),
            Self::List4(v) => list4(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union5FloatOrIntOrListJSONOrMapStringKeyJSONValueOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Float(v) => write!(f, "Float({:?})", v),
            Self::Map3(v) => write!(f, "Map3({:?})", v),
            Self::List4(v) => write!(f, "List4({:?})", v),
        }
    }
}
