// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::types::*;
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let client = CoreBamlClient::from_env()?;
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// ConsumeTestEnum - Generated BAML function
    pub async fn consume_test_enum(
        &self,
        input: crate::types::TestEnum,
    ) -> BamlResult<crate::types::TestEnum> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client.call_function("ConsumeTestEnum", context).await
    }

    /// ConsumeTestEnum (streaming) - Generated BAML function  
    pub async fn consume_test_enum_stream(
        &self,
        input: crate::types::TestEnum,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::TestEnum>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("ConsumeTestEnum", context)
            .await
    }
}
impl BamlClient {
    /// FnTestAliasedEnumOutput - Generated BAML function
    pub async fn fn_test_aliased_enum_output(
        &self,
        input: String,
    ) -> BamlResult<crate::types::TestEnum> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function("FnTestAliasedEnumOutput", context)
            .await
    }

    /// FnTestAliasedEnumOutput (streaming) - Generated BAML function  
    pub async fn fn_test_aliased_enum_output_stream(
        &self,
        input: String,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::TestEnum>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input)?;

        self.client
            .call_function_stream("FnTestAliasedEnumOutput", context)
            .await
    }
}
