// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type ExistingSystemComponent struct {
	Id          *int64                     `json:"id"`
	Name        *string                    `json:"name"`
	Type        *string                    `json:"type"`
	Category    *Union2KresourceOrKservice `json:"category"`
	Explanation *string                    `json:"explanation"`
}

func (c *ExistingSystemComponent) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ExistingSystemComponent" {
		panic(fmt.Sprintf("expected ExistingSystemComponent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "id":
			c.Id = func(param *cffi.CFFIValueHolder) *int64 {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *int64\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *int64 {
					if result == nil {
						return nil
					}
					return (result).(*int64)
				}(decoded)
			}(valueHolder)

		case "name":
			c.Name = func(param *cffi.CFFIValueHolder) *string {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *string\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					return (result).(*string)
				}(decoded)
			}(valueHolder)

		case "type":
			c.Type = func(param *cffi.CFFIValueHolder) *string {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *string\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					return (result).(*string)
				}(decoded)
			}(valueHolder)

		case "category":
			c.Category = func(param *cffi.CFFIValueHolder) *Union2KresourceOrKservice {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *Union2KresourceOrKservice\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *Union2KresourceOrKservice {
					if result == nil {
						return nil
					}
					return (result).(*Union2KresourceOrKservice)
				}(decoded)
			}(valueHolder)

		case "explanation":
			c.Explanation = func(param *cffi.CFFIValueHolder) *string {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *string\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					return (result).(*string)
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c ExistingSystemComponent) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["id"] = c.Id

	fields["name"] = c.Name

	fields["type"] = c.Type

	fields["category"] = c.Category

	fields["explanation"] = c.Explanation

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ExistingSystemComponent) BamlTypeName() string {
	return "ExistingSystemComponent"
}

func (u ExistingSystemComponent) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "ExistingSystemComponent",
	}
}

type UseMyUnion struct {
	U *Union3IntOrRecursive1OrString `json:"u"`
}

func (c *UseMyUnion) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "UseMyUnion" {
		panic(fmt.Sprintf("expected UseMyUnion, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "u":
			c.U = func(param *cffi.CFFIValueHolder) *Union3IntOrRecursive1OrString {
				fmt.Printf("\n=== FIELD DECODE ===\n")
				fmt.Printf("Expecting type: *Union3IntOrRecursive1OrString\n")
				fmt.Printf("===================\n")
				decoded := baml.Decode(param)
				return func(result any) *Union3IntOrRecursive1OrString {
					if result == nil {
						return nil
					}
					return (result).(*Union3IntOrRecursive1OrString)
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c UseMyUnion) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["u"] = c.U

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c UseMyUnion) BamlTypeName() string {
	return "UseMyUnion"
}

func (u UseMyUnion) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "UseMyUnion",
	}
}
