// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrganizationRequest = { org_id: string, org_slug: string, org_display_name: string, };
