// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

export type ListFunctionCallsRequest = { project_id: string, function_call_id: string | null, filter: Filter | null, };
