// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDefinition } from "./FunctionDefinition";
import type { FunctionSpan } from "./FunctionSpan";
import type { TypeDefinition } from "./TypeDefinition";

export type ListFunctionSpansResponse = { function_spans: Array<FunctionSpan>, function_definitions: Array<FunctionDefinition>, type_definitions: Array<TypeDefinition>, };
