// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
    // .context("Failed to create connection pool")?;
import type { Filter } from "./Filter";

export type ListFunctionSpansRequest = { project_id: string, function_call_id: string | null, filter: Filter | null, };
