// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiteralType } from "./LiteralType";
import type { TypeId } from "./TypeId";

export type TypeReference = { "type": "null" } | { "type": "string" } | { "type": "int" } | { "type": "float" } | { "type": "bool" } | { "type": "media" } | { "type": "class", type_id: TypeId, } | { "type": "enum", type_id: TypeId, } | { "type": "type_alias", type_id: TypeId, } | { "type": "array", items: TypeReference, } | { "type": "map", key: TypeReference, value: TypeReference, } | { "type": "union", any_of: Array<TypeReference>, } | { "type": "literal" } & LiteralType;
