// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"optional_nullable/baml_client/types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type parse struct{}

var Parse = &parse{}

// / Parse version of TestAllNull (Takes in string and returns types.NullableTypes)
func (*parse) TestAllNull(ctx context.Context, text string, opts ...CallOptionFunc) (types.NullableTypes, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestAllNull: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestAllNull", encoded)
	if err != nil {
		return types.NullableTypes{}, err
	}

	casted := (result).(types.NullableTypes)

	return casted, nil
}

// / Parse version of TestAllOptionalOmitted (Takes in string and returns types.OptionalFields)
func (*parse) TestAllOptionalOmitted(ctx context.Context, text string, opts ...CallOptionFunc) (types.OptionalFields, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestAllOptionalOmitted: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestAllOptionalOmitted", encoded)
	if err != nil {
		return types.OptionalFields{}, err
	}

	casted := (result).(types.OptionalFields)

	return casted, nil
}

// / Parse version of TestMixedOptionalNullable (Takes in string and returns types.MixedOptionalNullable)
func (*parse) TestMixedOptionalNullable(ctx context.Context, text string, opts ...CallOptionFunc) (types.MixedOptionalNullable, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestMixedOptionalNullable: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestMixedOptionalNullable", encoded)
	if err != nil {
		return types.MixedOptionalNullable{}, err
	}

	casted := (result).(types.MixedOptionalNullable)

	return casted, nil
}

// / Parse version of TestNullableTypes (Takes in string and returns types.NullableTypes)
func (*parse) TestNullableTypes(ctx context.Context, text string, opts ...CallOptionFunc) (types.NullableTypes, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestNullableTypes: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestNullableTypes", encoded)
	if err != nil {
		return types.NullableTypes{}, err
	}

	casted := (result).(types.NullableTypes)

	return casted, nil
}

// / Parse version of TestOptionalFields (Takes in string and returns types.OptionalFields)
func (*parse) TestOptionalFields(ctx context.Context, text string, opts ...CallOptionFunc) (types.OptionalFields, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestOptionalFields: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "TestOptionalFields", encoded)
	if err != nil {
		return types.OptionalFields{}, err
	}

	casted := (result).(types.OptionalFields)

	return casted, nil
}
