// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use crate::{source_map, types::*};
use baml_client_rust::{BamlClient as CoreBamlClient, BamlClientBuilder, BamlContext, BamlResult};
use futures::Stream;

/// Main BAML client for executing functions
#[derive(Debug, Clone)]
pub struct BamlClient {
    client: CoreBamlClient,
}

impl BamlClient {
    /// Create a new BAML client with default configuration
    pub fn new() -> BamlResult<Self> {
        let mut env_vars: std::collections::HashMap<String, String> = std::env::vars().collect();
        env_vars
            .entry("BAML_SRC".to_string())
            .or_insert_with(|| "./baml_src".to_string());

        // Prefer local baml_src during generated tests
        let mut last_error: Option<baml_client_rust::BamlError> = None;

        #[cfg(not(target_arch = "wasm32"))]
        {
            let local = std::path::Path::new("baml_src");
            if local.exists() {
                match CoreBamlClient::from_directory(local, env_vars.clone()) {
                    Ok(client) => return Ok(Self { client }),
                    Err(err) => {
                        #[cfg(debug_assertions)]
                        eprintln!("BamlClient::from_directory failed: {err}");
                        last_error = Some(err);
                    }
                }
            }
        }

        // Fall back to embedded source map
        let embedded_files: std::collections::HashMap<String, String> =
            source_map::baml_source_files()
                .into_iter()
                .map(|(path, contents)| (path.to_string(), contents.to_string()))
                .collect();
        if !embedded_files.is_empty() {
            match CoreBamlClient::from_file_content("./baml_src", &embedded_files, env_vars.clone())
            {
                Ok(client) => return Ok(Self { client }),
                Err(err) => {
                    #[cfg(debug_assertions)]
                    eprintln!("BamlClient::from_file_content failed: {err}");
                    last_error = Some(err);
                }
            }
        }

        let client = match CoreBamlClient::from_env() {
            Ok(client) => client,
            Err(err) => {
                #[cfg(debug_assertions)]
                if let Some(prev) = &last_error {
                    eprintln!("BamlClient::from_env failed after embedded attempts: {prev}");
                }
                return Err(err);
            }
        };
        Ok(Self { client })
    }

    /// Create a new BAML client from a directory containing BAML files
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_directory<P: AsRef<std::path::Path>>(path: P) -> BamlResult<Self> {
        let client = CoreBamlClient::from_directory(path, std::env::vars().collect())?;
        Ok(Self { client })
    }

    /// Create a new BAML client with custom configuration
    pub fn builder() -> BamlClientBuilder {
        BamlClientBuilder::new()
    }

    /// Create a new BAML client with a custom core client
    pub fn with_core_client(client: CoreBamlClient) -> Self {
        Self { client }
    }

    /// Get access to the underlying core client
    pub fn core_client(&self) -> &CoreBamlClient {
        &self.client
    }
}

impl Default for BamlClient {
    fn default() -> Self {
        Self::new().expect("Failed to create default BamlClient")
    }
}
impl BamlClient {
    /// TestEmptyArrays - Generated BAML function
    pub async fn test_empty_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::SimpleArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestEmptyArrays", context).await
    }

    /// TestEmptyArrays (streaming) - Generated BAML function  
    pub async fn test_empty_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::SimpleArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestEmptyArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestLargeArrays - Generated BAML function
    pub async fn test_large_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::SimpleArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestLargeArrays", context).await
    }

    /// TestLargeArrays (streaming) - Generated BAML function  
    pub async fn test_large_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::SimpleArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestLargeArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestMixedArrays - Generated BAML function
    pub async fn test_mixed_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::MixedArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestMixedArrays", context).await
    }

    /// TestMixedArrays (streaming) - Generated BAML function  
    pub async fn test_mixed_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::MixedArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestMixedArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestNestedArrays - Generated BAML function
    pub async fn test_nested_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::NestedArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestNestedArrays", context).await
    }

    /// TestNestedArrays (streaming) - Generated BAML function  
    pub async fn test_nested_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::NestedArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestNestedArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestObjectArrays - Generated BAML function
    pub async fn test_object_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::ObjectArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestObjectArrays", context).await
    }

    /// TestObjectArrays (streaming) - Generated BAML function  
    pub async fn test_object_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::ObjectArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestObjectArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestSimpleArrays - Generated BAML function
    pub async fn test_simple_arrays(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<crate::types::SimpleArrays> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client.call_function("TestSimpleArrays", context).await
    }

    /// TestSimpleArrays (streaming) - Generated BAML function  
    pub async fn test_simple_arrays_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<crate::types::SimpleArrays>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestSimpleArrays", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevel3DArray - Generated BAML function
    pub async fn test_top_level3_d_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<Vec<Vec<String>>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevel3DArray", context)
            .await
    }

    /// TestTopLevel3DArray (streaming) - Generated BAML function  
    pub async fn test_top_level3_d_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<Vec<Vec<String>>>>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevel3DArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelArrayOfMaps - Generated BAML function
    pub async fn test_top_level_array_of_maps(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<std::collections::HashMap<String, i64>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelArrayOfMaps", context)
            .await
    }

    /// TestTopLevelArrayOfMaps (streaming) - Generated BAML function  
    pub async fn test_top_level_array_of_maps_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<Vec<std::collections::HashMap<String, i64>>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelArrayOfMaps", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelBoolArray - Generated BAML function
    pub async fn test_top_level_bool_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<bool>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelBoolArray", context)
            .await
    }

    /// TestTopLevelBoolArray (streaming) - Generated BAML function  
    pub async fn test_top_level_bool_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<bool>>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelBoolArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelEmptyArray - Generated BAML function
    pub async fn test_top_level_empty_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<String>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelEmptyArray", context)
            .await
    }

    /// TestTopLevelEmptyArray (streaming) - Generated BAML function  
    pub async fn test_top_level_empty_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<String>>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelEmptyArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelFloatArray - Generated BAML function
    pub async fn test_top_level_float_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<f64>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelFloatArray", context)
            .await
    }

    /// TestTopLevelFloatArray (streaming) - Generated BAML function  
    pub async fn test_top_level_float_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<f64>>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelFloatArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelIntArray - Generated BAML function
    pub async fn test_top_level_int_array(&self, input: impl Into<String>) -> BamlResult<Vec<i64>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelIntArray", context)
            .await
    }

    /// TestTopLevelIntArray (streaming) - Generated BAML function  
    pub async fn test_top_level_int_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<i64>>>> + Send + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelIntArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelMixedArray - Generated BAML function
    pub async fn test_top_level_mixed_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<crate::types::Union3BoolOrIntOrString>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelMixedArray", context)
            .await
    }

    /// TestTopLevelMixedArray (streaming) - Generated BAML function  
    pub async fn test_top_level_mixed_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<
                    baml_client_rust::StreamState<Vec<crate::types::Union3BoolOrIntOrString>>,
                >,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelMixedArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelNestedArray - Generated BAML function
    pub async fn test_top_level_nested_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<Vec<i64>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelNestedArray", context)
            .await
    }

    /// TestTopLevelNestedArray (streaming) - Generated BAML function  
    pub async fn test_top_level_nested_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<Vec<i64>>>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelNestedArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelNullableArray - Generated BAML function
    pub async fn test_top_level_nullable_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<Option<String>>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelNullableArray", context)
            .await
    }

    /// TestTopLevelNullableArray (streaming) - Generated BAML function  
    pub async fn test_top_level_nullable_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<Option<String>>>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelNullableArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelObjectArray - Generated BAML function
    pub async fn test_top_level_object_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<crate::types::User>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelObjectArray", context)
            .await
    }

    /// TestTopLevelObjectArray (streaming) - Generated BAML function  
    pub async fn test_top_level_object_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<
                Item = BamlResult<baml_client_rust::StreamState<Vec<crate::types::User>>>,
            > + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelObjectArray", context)
            .await
    }
}
impl BamlClient {
    /// TestTopLevelStringArray - Generated BAML function
    pub async fn test_top_level_string_array(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<Vec<String>> {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function("TestTopLevelStringArray", context)
            .await
    }

    /// TestTopLevelStringArray (streaming) - Generated BAML function  
    pub async fn test_top_level_string_array_stream(
        &self,
        input: impl Into<String>,
    ) -> BamlResult<
        impl futures::Stream<Item = BamlResult<baml_client_rust::StreamState<Vec<String>>>>
            + Send
            + Sync,
    > {
        let mut context = BamlContext::new();
        context = context.set_arg("input", input.into())?;

        // Include environment variables in the context
        context = context.set_env_vars(std::env::vars());

        self.client
            .call_function_stream("TestTopLevelStringArray", context)
            .await
    }
}
