// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::convert::TryFrom;

/// Represents the BAML `null` type in Rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct NullValue;

impl baml_client_rust::types::ToBamlValue for NullValue {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        Ok(baml_client_rust::types::BamlValue::Null)
    }
}

impl baml_client_rust::types::FromBamlValue for NullValue {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Null => Ok(NullValue),
            other => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected null, got {:?}",
                other
            ))),
        }
    }
}

#[derive(Debug, Clone)]
pub enum RustLiteralKind {
    String,
    Int,
    Bool,
}

macro_rules! define_baml_media_type {
    ($name:ident, $variant:ident) => {
        #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
        #[serde(transparent)]
        pub struct $name {
            inner: baml_types::BamlMedia,
        }

        impl $name {
            pub fn new(media: baml_types::BamlMedia) -> baml_client_rust::BamlResult<Self> {
                if media.media_type == baml_types::BamlMediaType::$variant {
                    Ok(Self { inner: media })
                } else {
                    Err(baml_client_rust::BamlError::deserialization(format!(
                        "Expected {:?} media, got {:?}",
                        baml_types::BamlMediaType::$variant,
                        media.media_type
                    )))
                }
            }

            pub fn from_url(url: impl Into<String>, mime_type: Option<String>) -> Self {
                Self {
                    inner: baml_types::BamlMedia::url(
                        baml_types::BamlMediaType::$variant,
                        url.into(),
                        mime_type,
                    ),
                }
            }

            pub fn from_base64(base64: impl Into<String>, mime_type: Option<String>) -> Self {
                Self {
                    inner: baml_types::BamlMedia::base64(
                        baml_types::BamlMediaType::$variant,
                        base64.into(),
                        mime_type,
                    ),
                }
            }

            pub fn into_inner(self) -> baml_types::BamlMedia {
                self.inner
            }

            pub fn as_inner(&self) -> &baml_types::BamlMedia {
                &self.inner
            }
        }

        impl TryFrom<baml_types::BamlMedia> for $name {
            type Error = baml_client_rust::BamlError;

            fn try_from(media: baml_types::BamlMedia) -> std::result::Result<Self, Self::Error> {
                Self::new(media)
            }
        }

        impl From<$name> for baml_types::BamlMedia {
            fn from(value: $name) -> Self {
                value.inner
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self {
                    inner: baml_types::BamlMedia::base64(
                        baml_types::BamlMediaType::$variant,
                        String::new(),
                        None,
                    ),
                }
            }
        }

        impl baml_client_rust::types::ToBamlValue for $name {
            fn to_baml_value(
                self,
            ) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
                Ok(baml_client_rust::types::BamlValue::Media(self.inner))
            }
        }

        impl baml_client_rust::types::FromBamlValue for $name {
            fn from_baml_value(
                value: baml_client_rust::types::BamlValue,
            ) -> baml_client_rust::BamlResult<Self> {
                match value {
                    baml_client_rust::types::BamlValue::Media(media) => {
                        if media.media_type == baml_types::BamlMediaType::$variant {
                            Ok(Self { inner: media })
                        } else {
                            Err(baml_client_rust::BamlError::deserialization(format!(
                                "Expected {:?} media, got {:?}",
                                baml_types::BamlMediaType::$variant,
                                media.media_type
                            )))
                        }
                    }
                    other => Err(baml_client_rust::BamlError::deserialization(format!(
                        "Expected media value, got {:?}",
                        other
                    ))),
                }
            }
        }
    };
}

define_baml_media_type!(BamlImage, Image);
define_baml_media_type!(BamlAudio, Audio);
define_baml_media_type!(BamlPdf, Pdf);
define_baml_media_type!(BamlVideo, Video);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArrayWithConstraints {
    pub non_empty_strings: Vec<String>,

    pub limited_ints: Vec<i64>,

    pub positive_floats: Vec<f64>,
}

impl ArrayWithConstraints {
    /// Create a new ArrayWithConstraints instance
    pub fn new(
        non_empty_strings: Vec<String>,
        limited_ints: Vec<i64>,
        positive_floats: Vec<f64>,
    ) -> Self {
        Self {
            non_empty_strings,
            limited_ints,
            positive_floats,
        }
    }
}

impl Default for ArrayWithConstraints {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ArrayWithConstraints {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "nonEmptyStrings".to_string(),
            self.non_empty_strings.to_baml_value()?,
        );
        map.insert(
            "limitedInts".to_string(),
            self.limited_ints.to_baml_value()?,
        );
        map.insert(
            "positiveFloats".to_string(),
            self.positive_floats.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "ArrayWithConstraints".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ArrayWithConstraints {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let non_empty_strings = match map.get("nonEmptyStrings") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nonEmptyStrings' in ArrayWithConstraints"
                        )));
                    }
                };
                let limited_ints = match map.get("limitedInts") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'limitedInts' in ArrayWithConstraints"
                        )));
                    }
                };
                let positive_floats = match map.get("positiveFloats") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'positiveFloats' in ArrayWithConstraints"
                        )));
                    }
                };
                Ok(Self::new(non_empty_strings, limited_ints, positive_floats))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MixedArrays {
    pub primitive_array: Vec<crate::types::Union4BoolOrFloatOrIntOrString>,

    pub nullable_array: Vec<Option<String>>,

    pub optional_items: Vec<Option<String>>,

    pub array_of_arrays: Vec<Vec<String>>,

    pub complex_mixed: Vec<crate::types::Union3ProductOrTagOrUser>,
}

impl MixedArrays {
    /// Create a new MixedArrays instance
    pub fn new(
        primitive_array: Vec<crate::types::Union4BoolOrFloatOrIntOrString>,
        nullable_array: Vec<Option<String>>,
        optional_items: Vec<Option<String>>,
        array_of_arrays: Vec<Vec<String>>,
        complex_mixed: Vec<crate::types::Union3ProductOrTagOrUser>,
    ) -> Self {
        Self {
            primitive_array,
            nullable_array,
            optional_items,
            array_of_arrays,
            complex_mixed,
        }
    }
}

impl Default for MixedArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "primitiveArray".to_string(),
            self.primitive_array.to_baml_value()?,
        );
        map.insert(
            "nullableArray".to_string(),
            self.nullable_array.to_baml_value()?,
        );
        map.insert(
            "optionalItems".to_string(),
            self.optional_items.to_baml_value()?,
        );
        map.insert(
            "arrayOfArrays".to_string(),
            self.array_of_arrays.to_baml_value()?,
        );
        map.insert(
            "complexMixed".to_string(),
            self.complex_mixed.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let primitive_array = match map.get("primitiveArray") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'primitiveArray' in MixedArrays"
                        )));
                    }
                };
                let nullable_array = match map.get("nullableArray") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableArray' in MixedArrays"
                        )));
                    }
                };
                let optional_items = match map.get("optionalItems") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalItems' in MixedArrays"
                        )));
                    }
                };
                let array_of_arrays = match map.get("arrayOfArrays") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'arrayOfArrays' in MixedArrays"
                        )));
                    }
                };
                let complex_mixed = match map.get("complexMixed") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'complexMixed' in MixedArrays"
                        )));
                    }
                };
                Ok(Self::new(
                    primitive_array,
                    nullable_array,
                    optional_items,
                    array_of_arrays,
                    complex_mixed,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NestedArrays {
    pub matrix: Vec<Vec<i64>>,

    pub string_matrix: Vec<Vec<String>>,

    pub three_dimensional: Vec<Vec<Vec<f64>>>,
}

impl NestedArrays {
    /// Create a new NestedArrays instance
    pub fn new(
        matrix: Vec<Vec<i64>>,
        string_matrix: Vec<Vec<String>>,
        three_dimensional: Vec<Vec<Vec<f64>>>,
    ) -> Self {
        Self {
            matrix,
            string_matrix,
            three_dimensional,
        }
    }
}

impl Default for NestedArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NestedArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("matrix".to_string(), self.matrix.to_baml_value()?);
        map.insert(
            "stringMatrix".to_string(),
            self.string_matrix.to_baml_value()?,
        );
        map.insert(
            "threeDimensional".to_string(),
            self.three_dimensional.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "NestedArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NestedArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let matrix = match map.get("matrix") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'matrix' in NestedArrays"
                        )));
                    }
                };
                let string_matrix = match map.get("stringMatrix") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringMatrix' in NestedArrays"
                        )));
                    }
                };
                let three_dimensional = match map.get("threeDimensional") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'threeDimensional' in NestedArrays"
                        )));
                    }
                };
                Ok(Self::new(matrix, string_matrix, three_dimensional))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ObjectArrays {
    pub users: Vec<crate::types::User>,

    pub products: Vec<crate::types::Product>,

    pub tags: Vec<crate::types::Tag>,
}

impl ObjectArrays {
    /// Create a new ObjectArrays instance
    pub fn new(
        users: Vec<crate::types::User>,
        products: Vec<crate::types::Product>,
        tags: Vec<crate::types::Tag>,
    ) -> Self {
        Self {
            users,
            products,
            tags,
        }
    }
}

impl Default for ObjectArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ObjectArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("users".to_string(), self.users.to_baml_value()?);
        map.insert("products".to_string(), self.products.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "ObjectArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ObjectArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let users = match map.get("users") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'users' in ObjectArrays"
                        )));
                    }
                };
                let products = match map.get("products") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'products' in ObjectArrays"
                        )));
                    }
                };
                let tags = match map.get("tags") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in ObjectArrays"
                        )));
                    }
                };
                Ok(Self::new(users, products, tags))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Product {
    pub id: i64,

    pub name: String,

    pub price: f64,

    pub tags: Vec<String>,

    pub in_stock: bool,
}

impl Product {
    /// Create a new Product instance
    pub fn new(id: i64, name: String, price: f64, tags: Vec<String>, in_stock: bool) -> Self {
        Self {
            id,
            name,
            price,
            tags,
            in_stock,
        }
    }
}

impl Default for Product {
    fn default() -> Self {
        Self::new(0, String::new(), 0.0, Vec::new(), false)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Product {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("price".to_string(), self.price.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        map.insert("inStock".to_string(), self.in_stock.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Product".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Product {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = match map.get("id") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            0
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => 0,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Product"
                        )));
                    }
                };
                let name = match map.get("name") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            String::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => String::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Product"
                        )));
                    }
                };
                let price = match map.get("price") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            0.0
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => 0.0,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'price' in Product"
                        )));
                    }
                };
                let tags = match map.get("tags") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in Product"
                        )));
                    }
                };
                let in_stock = match map.get("inStock") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            false
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => false,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'inStock' in Product"
                        )));
                    }
                };
                Ok(Self::new(id, name, price, tags, in_stock))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SimpleArrays {
    pub strings: Vec<String>,

    pub integers: Vec<i64>,

    pub floats: Vec<f64>,

    pub booleans: Vec<bool>,
}

impl SimpleArrays {
    /// Create a new SimpleArrays instance
    pub fn new(
        strings: Vec<String>,
        integers: Vec<i64>,
        floats: Vec<f64>,
        booleans: Vec<bool>,
    ) -> Self {
        Self {
            strings,
            integers,
            floats,
            booleans,
        }
    }
}

impl Default for SimpleArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for SimpleArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("strings".to_string(), self.strings.to_baml_value()?);
        map.insert("integers".to_string(), self.integers.to_baml_value()?);
        map.insert("floats".to_string(), self.floats.to_baml_value()?);
        map.insert("booleans".to_string(), self.booleans.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "SimpleArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for SimpleArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let strings = match map.get("strings") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'strings' in SimpleArrays"
                        )));
                    }
                };
                let integers = match map.get("integers") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'integers' in SimpleArrays"
                        )));
                    }
                };
                let floats = match map.get("floats") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'floats' in SimpleArrays"
                        )));
                    }
                };
                let booleans = match map.get("booleans") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            Vec::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => Vec::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'booleans' in SimpleArrays"
                        )));
                    }
                };
                Ok(Self::new(strings, integers, floats, booleans))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Tag {
    pub id: i64,

    pub name: String,

    pub color: String,
}

impl Tag {
    /// Create a new Tag instance
    pub fn new(id: i64, name: String, color: String) -> Self {
        Self { id, name, color }
    }
}

impl Default for Tag {
    fn default() -> Self {
        Self::new(0, String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Tag {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("color".to_string(), self.color.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Tag".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Tag {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = match map.get("id") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            0
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => 0,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Tag"
                        )));
                    }
                };
                let name = match map.get("name") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            String::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => String::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Tag"
                        )));
                    }
                };
                let color = match map.get("color") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            String::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => String::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'color' in Tag"
                        )));
                    }
                };
                Ok(Self::new(id, name, color))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct User {
    pub id: i64,

    pub name: String,

    pub email: String,

    pub is_active: bool,
}

impl User {
    /// Create a new User instance
    pub fn new(id: i64, name: String, email: String, is_active: bool) -> Self {
        Self {
            id,
            name,
            email,
            is_active,
        }
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new(0, String::new(), String::new(), false)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for User {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("email".to_string(), self.email.to_baml_value()?);
        map.insert("isActive".to_string(), self.is_active.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "User".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for User {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = match map.get("id") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            0
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => 0,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in User"
                        )));
                    }
                };
                let name = match map.get("name") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            String::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => String::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in User"
                        )));
                    }
                };
                let email = match map.get("email") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            String::new()
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => String::new(),
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'email' in User"
                        )));
                    }
                };
                let is_active = match map.get("isActive") {
                    Some(value) => match value {
                        baml_client_rust::types::BamlValue::Null
                            if baml_client_rust::types::is_partial_deserialization() =>
                        {
                            false
                        }
                        _ => {
                            baml_client_rust::types::FromBamlValue::from_baml_value(value.clone())?
                        }
                    },
                    None if baml_client_rust::types::is_partial_deserialization() => false,
                    None => {
                        return Err(baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'isActive' in User"
                        )));
                    }
                };
                Ok(Self::new(id, name, email, is_active))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3BoolOrIntOrString {
    String(String),
    Int(i64),
    Bool(bool),
}

impl Union3BoolOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union3BoolOrIntOrString
impl Union3BoolOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3BoolOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}

impl Default for Union3BoolOrIntOrString {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union3BoolOrIntOrString {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::String(v) => v.to_baml_value(),
            Self::Int(v) => v.to_baml_value(),
            Self::Bool(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union3BoolOrIntOrString {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try String variant
        if let Ok(variant_value) = String::from_baml_value(value.clone()) {
            return Ok(Self::String(variant_value));
        }
        // Try Int variant
        if let Ok(variant_value) = i64::from_baml_value(value.clone()) {
            return Ok(Self::Int(variant_value));
        }
        // Try Bool variant
        if let Ok(variant_value) = bool::from_baml_value(value.clone()) {
            return Ok(Self::Bool(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union3BoolOrIntOrString",
            value
        )))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3ProductOrTagOrUser {
    User(crate::types::User),
    Product(crate::types::Product),
    Tag(crate::types::Tag),
}

impl Union3ProductOrTagOrUser {
    /// Check if this union is a User variant
    pub fn is_user(&self) -> bool {
        matches!(self, Self::User(_))
    }
    /// Get the User value if this union contains it
    pub fn as_user(&self) -> Option<&crate::types::User> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the User value, consuming the union
    pub fn into_user(self) -> Option<crate::types::User> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the User value if this union contains it
    pub fn as_user_mut(&mut self) -> Option<&mut crate::types::User> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a User variant
    pub fn user(value: crate::types::User) -> Self {
        Self::User(value)
    }

    /// Check if this union is a Product variant
    pub fn is_product(&self) -> bool {
        matches!(self, Self::Product(_))
    }
    /// Get the Product value if this union contains it
    pub fn as_product(&self) -> Option<&crate::types::Product> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Product value, consuming the union
    pub fn into_product(self) -> Option<crate::types::Product> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Product value if this union contains it
    pub fn as_product_mut(&mut self) -> Option<&mut crate::types::Product> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a Product variant
    pub fn product(value: crate::types::Product) -> Self {
        Self::Product(value)
    }

    /// Check if this union is a Tag variant
    pub fn is_tag(&self) -> bool {
        matches!(self, Self::Tag(_))
    }
    /// Get the Tag value if this union contains it
    pub fn as_tag(&self) -> Option<&crate::types::Tag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Tag value, consuming the union
    pub fn into_tag(self) -> Option<crate::types::Tag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Tag value if this union contains it
    pub fn as_tag_mut(&mut self) -> Option<&mut crate::types::Tag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a Tag variant
    pub fn tag(value: crate::types::Tag) -> Self {
        Self::Tag(value)
    }
}

/// Pattern matching helper for Union3ProductOrTagOrUser
impl Union3ProductOrTagOrUser {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        user: impl FnOnce(&crate::types::User) -> T,
        product: impl FnOnce(&crate::types::Product) -> T,
        tag: impl FnOnce(&crate::types::Tag) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
            Self::Tag(v) => tag(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        user: impl FnOnce(crate::types::User) -> T,
        product: impl FnOnce(crate::types::Product) -> T,
        tag: impl FnOnce(crate::types::Tag) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
            Self::Tag(v) => tag(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3ProductOrTagOrUser {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::User(v) => write!(f, "User({:?})", v),
            Self::Product(v) => write!(f, "Product({:?})", v),
            Self::Tag(v) => write!(f, "Tag({:?})", v),
        }
    }
}

impl Default for Union3ProductOrTagOrUser {
    fn default() -> Self {
        Self::User(Default::default())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union3ProductOrTagOrUser {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::User(v) => v.to_baml_value(),
            Self::Product(v) => v.to_baml_value(),
            Self::Tag(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union3ProductOrTagOrUser {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try User variant
        if let Ok(variant_value) = crate::types::User::from_baml_value(value.clone()) {
            return Ok(Self::User(variant_value));
        }
        // Try Product variant
        if let Ok(variant_value) = crate::types::Product::from_baml_value(value.clone()) {
            return Ok(Self::Product(variant_value));
        }
        // Try Tag variant
        if let Ok(variant_value) = crate::types::Tag::from_baml_value(value.clone()) {
            return Ok(Self::Tag(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union3ProductOrTagOrUser",
            value
        )))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union4BoolOrFloatOrIntOrString {
    String(String),
    Int(i64),
    Float(f64),
    Bool(bool),
}

impl Union4BoolOrFloatOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Float variant
    pub fn is_float(&self) -> bool {
        matches!(self, Self::Float(_))
    }
    /// Get the Float value if this union contains it
    pub fn as_float(&self) -> Option<&f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Float value, consuming the union
    pub fn into_float(self) -> Option<f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Float value if this union contains it
    pub fn as_float_mut(&mut self) -> Option<&mut f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Float variant
    pub fn float(value: f64) -> Self {
        Self::Float(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union4BoolOrFloatOrIntOrString
impl Union4BoolOrFloatOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        float: impl FnOnce(&f64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        float: impl FnOnce(f64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union4BoolOrFloatOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Float(v) => write!(f, "Float({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}

impl Default for Union4BoolOrFloatOrIntOrString {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union4BoolOrFloatOrIntOrString {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::String(v) => v.to_baml_value(),
            Self::Int(v) => v.to_baml_value(),
            Self::Float(v) => v.to_baml_value(),
            Self::Bool(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union4BoolOrFloatOrIntOrString {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try String variant
        if let Ok(variant_value) = String::from_baml_value(value.clone()) {
            return Ok(Self::String(variant_value));
        }
        // Try Int variant
        if let Ok(variant_value) = i64::from_baml_value(value.clone()) {
            return Ok(Self::Int(variant_value));
        }
        // Try Float variant
        if let Ok(variant_value) = f64::from_baml_value(value.clone()) {
            return Ok(Self::Float(variant_value));
        }
        // Try Bool variant
        if let Ok(variant_value) = bool::from_baml_value(value.clone()) {
            return Ok(Self::Bool(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union4BoolOrFloatOrIntOrString",
            value
        )))
    }
}
