// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//
//	$ go install github.com/boundaryml/baml/baml-cli
package baml_client

import (
	"context"
	"semantic_streaming/baml_client/stream_types"
	"semantic_streaming/baml_client/types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() TFinal {
	return *s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() TStream {
	return *s.as_stream
}

// / Streaming version of MakeClassWithBlockDone
func (*stream) MakeClassWithBlockDone(ctx context.Context, opts ...CallOptionFunc) <-chan StreamValue[*stream_types.ClassWithBlockDone, types.ClassWithBlockDone] {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	channel := make(chan StreamValue[*stream_types.ClassWithBlockDone, types.ClassWithBlockDone])
	raw, err := bamlRuntime.CallFunctionStream(ctx, "MakeClassWithBlockDone", encoded)
	if err != nil {
		close(channel)
		return channel
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-raw:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.ClassWithBlockDone)
					channel <- StreamValue[*stream_types.ClassWithBlockDone, types.ClassWithBlockDone]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := (result.StreamData).(*stream_types.ClassWithBlockDone)
					channel <- StreamValue[*stream_types.ClassWithBlockDone, types.ClassWithBlockDone]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel
}

// / Streaming version of MakeClassWithExternalDone
func (*stream) MakeClassWithExternalDone(ctx context.Context, opts ...CallOptionFunc) <-chan StreamValue[*stream_types.ClassWithoutDone, types.ClassWithoutDone] {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	channel := make(chan StreamValue[*stream_types.ClassWithoutDone, types.ClassWithoutDone])
	raw, err := bamlRuntime.CallFunctionStream(ctx, "MakeClassWithExternalDone", encoded)
	if err != nil {
		close(channel)
		return channel
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-raw:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.ClassWithoutDone)
					channel <- StreamValue[*stream_types.ClassWithoutDone, types.ClassWithoutDone]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := (result.StreamData).(*stream_types.ClassWithoutDone)
					channel <- StreamValue[*stream_types.ClassWithoutDone, types.ClassWithoutDone]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel
}

// / Streaming version of MakeSemanticContainer
func (*stream) MakeSemanticContainer(ctx context.Context, opts ...CallOptionFunc) <-chan StreamValue[*stream_types.SemanticContainer, types.SemanticContainer] {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	encoded, err := baml.EncodeRoot(args)
	if err != nil {
		panic(err)
	}

	channel := make(chan StreamValue[*stream_types.SemanticContainer, types.SemanticContainer])
	raw, err := bamlRuntime.CallFunctionStream(ctx, "MakeSemanticContainer", encoded)
	if err != nil {
		close(channel)
		return channel
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-raw:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.SemanticContainer)
					channel <- StreamValue[*stream_types.SemanticContainer, types.SemanticContainer]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := (result.StreamData).(*stream_types.SemanticContainer)
					channel <- StreamValue[*stream_types.SemanticContainer, types.SemanticContainer]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel
}
